// Code generated by ent, DO NOT EDIT.

package videotask

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the videotask type in the database.
	Label = "video_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldExternalModel holds the string denoting the external_model field in the database.
	FieldExternalModel = "external_model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldIdempotencyKeyHash holds the string denoting the idempotency_key_hash field in the database.
	FieldIdempotencyKeyHash = "idempotency_key_hash"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldProviderSubmissionToken holds the string denoting the provider_submission_token field in the database.
	FieldProviderSubmissionToken = "provider_submission_token"
	// FieldRequestPayload holds the string denoting the request_payload field in the database.
	FieldRequestPayload = "request_payload"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldUpstreamStatus holds the string denoting the upstream_status field in the database.
	FieldUpstreamStatus = "upstream_status"
	// FieldResultURL holds the string denoting the result_url field in the database.
	FieldResultURL = "result_url"
	// FieldResultURLExpiresAt holds the string denoting the result_url_expires_at field in the database.
	FieldResultURLExpiresAt = "result_url_expires_at"
	// FieldResultContentType holds the string denoting the result_content_type field in the database.
	FieldResultContentType = "result_content_type"
	// FieldResultDurationSeconds holds the string denoting the result_duration_seconds field in the database.
	FieldResultDurationSeconds = "result_duration_seconds"
	// FieldResultWidth holds the string denoting the result_width field in the database.
	FieldResultWidth = "result_width"
	// FieldResultHeight holds the string denoting the result_height field in the database.
	FieldResultHeight = "result_height"
	// FieldPricingUnit holds the string denoting the pricing_unit field in the database.
	FieldPricingUnit = "pricing_unit"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldEstimatedUnits holds the string denoting the estimated_units field in the database.
	FieldEstimatedUnits = "estimated_units"
	// FieldEstimatedAmount holds the string denoting the estimated_amount field in the database.
	FieldEstimatedAmount = "estimated_amount"
	// FieldFrozenAmount holds the string denoting the frozen_amount field in the database.
	FieldFrozenAmount = "frozen_amount"
	// FieldSettledAmount holds the string denoting the settled_amount field in the database.
	FieldSettledAmount = "settled_amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldBillingMode holds the string denoting the billing_mode field in the database.
	FieldBillingMode = "billing_mode"
	// FieldBillingStatus holds the string denoting the billing_status field in the database.
	FieldBillingStatus = "billing_status"
	// FieldBillingReference holds the string denoting the billing_reference field in the database.
	FieldBillingReference = "billing_reference"
	// FieldSubmissionAttempts holds the string denoting the submission_attempts field in the database.
	FieldSubmissionAttempts = "submission_attempts"
	// FieldPollAttempts holds the string denoting the poll_attempts field in the database.
	FieldPollAttempts = "poll_attempts"
	// FieldSettlementAttempts holds the string denoting the settlement_attempts field in the database.
	FieldSettlementAttempts = "settlement_attempts"
	// FieldNextPollAt holds the string denoting the next_poll_at field in the database.
	FieldNextPollAt = "next_poll_at"
	// FieldLeaseOwner holds the string denoting the lease_owner field in the database.
	FieldLeaseOwner = "lease_owner"
	// FieldLeaseExpiresAt holds the string denoting the lease_expires_at field in the database.
	FieldLeaseExpiresAt = "lease_expires_at"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldLastErrorMessage holds the string denoting the last_error_message field in the database.
	FieldLastErrorMessage = "last_error_message"
	// FieldLastErrorRetryable holds the string denoting the last_error_retryable field in the database.
	FieldLastErrorRetryable = "last_error_retryable"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// Table holds the table name of the videotask in the database.
	Table = "video_tasks"
)

// Columns holds all SQL columns for videotask fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldUserID,
	FieldAPIKeyID,
	FieldSubscriptionID,
	FieldGroupID,
	FieldAccountID,
	FieldPlatform,
	FieldProvider,
	FieldOperation,
	FieldExternalModel,
	FieldUpstreamModel,
	FieldIdempotencyKeyHash,
	FieldRequestHash,
	FieldProviderSubmissionToken,
	FieldRequestPayload,
	FieldStatus,
	FieldUpstreamTaskID,
	FieldUpstreamStatus,
	FieldResultURL,
	FieldResultURLExpiresAt,
	FieldResultContentType,
	FieldResultDurationSeconds,
	FieldResultWidth,
	FieldResultHeight,
	FieldPricingUnit,
	FieldUnitPrice,
	FieldEstimatedUnits,
	FieldEstimatedAmount,
	FieldFrozenAmount,
	FieldSettledAmount,
	FieldCurrency,
	FieldBillingMode,
	FieldBillingStatus,
	FieldBillingReference,
	FieldSubmissionAttempts,
	FieldPollAttempts,
	FieldSettlementAttempts,
	FieldNextPollAt,
	FieldLeaseOwner,
	FieldLeaseExpiresAt,
	FieldLastErrorCode,
	FieldLastErrorMessage,
	FieldLastErrorRetryable,
	FieldVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSubmittedAt,
	FieldStartedAt,
	FieldFinishedAt,
	FieldSettledAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// ExternalModelValidator is a validator for the "external_model" field. It is called by the builders before save.
	ExternalModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// DefaultIdempotencyKeyHash holds the default value on creation for the "idempotency_key_hash" field.
	DefaultIdempotencyKeyHash string
	// IdempotencyKeyHashValidator is a validator for the "idempotency_key_hash" field. It is called by the builders before save.
	IdempotencyKeyHashValidator func(string) error
	// RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	RequestHashValidator func(string) error
	// ProviderSubmissionTokenValidator is a validator for the "provider_submission_token" field. It is called by the builders before save.
	ProviderSubmissionTokenValidator func(string) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// UpstreamStatusValidator is a validator for the "upstream_status" field. It is called by the builders before save.
	UpstreamStatusValidator func(string) error
	// ResultContentTypeValidator is a validator for the "result_content_type" field. It is called by the builders before save.
	ResultContentTypeValidator func(string) error
	// PricingUnitValidator is a validator for the "pricing_unit" field. It is called by the builders before save.
	PricingUnitValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// BillingModeValidator is a validator for the "billing_mode" field. It is called by the builders before save.
	BillingModeValidator func(string) error
	// BillingStatusValidator is a validator for the "billing_status" field. It is called by the builders before save.
	BillingStatusValidator func(string) error
	// BillingReferenceValidator is a validator for the "billing_reference" field. It is called by the builders before save.
	BillingReferenceValidator func(string) error
	// DefaultSubmissionAttempts holds the default value on creation for the "submission_attempts" field.
	DefaultSubmissionAttempts int
	// DefaultPollAttempts holds the default value on creation for the "poll_attempts" field.
	DefaultPollAttempts int
	// DefaultSettlementAttempts holds the default value on creation for the "settlement_attempts" field.
	DefaultSettlementAttempts int
	// LeaseOwnerValidator is a validator for the "lease_owner" field. It is called by the builders before save.
	LeaseOwnerValidator func(string) error
	// LastErrorCodeValidator is a validator for the "last_error_code" field. It is called by the builders before save.
	LastErrorCodeValidator func(string) error
	// DefaultLastErrorRetryable holds the default value on creation for the "last_error_retryable" field.
	DefaultLastErrorRetryable bool
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Platform defines the type for the "platform" enum field.
type Platform string

// Platform values.
const (
	PlatformVideo Platform = "video"
)

func (pl Platform) String() string {
	return string(pl)
}

// PlatformValidator is a validator for the "platform" field enum values. It is called by the builders before save.
func PlatformValidator(pl Platform) error {
	switch pl {
	case PlatformVideo:
		return nil
	default:
		return fmt.Errorf("videotask: invalid enum value for platform field: %q", pl)
	}
}

// Provider defines the type for the "provider" enum field.
type Provider string

// Provider values.
const (
	ProviderSeedance Provider = "seedance"
	ProviderKling    Provider = "kling"
)

func (pr Provider) String() string {
	return string(pr)
}

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr Provider) error {
	switch pr {
	case ProviderSeedance, ProviderKling:
		return nil
	default:
		return fmt.Errorf("videotask: invalid enum value for provider field: %q", pr)
	}
}

// Operation defines the type for the "operation" enum field.
type Operation string

// Operation values.
const (
	OperationGeneration Operation = "generation"
	OperationEdit       Operation = "edit"
	OperationExtension  Operation = "extension"
)

func (o Operation) String() string {
	return string(o)
}

// OperationValidator is a validator for the "operation" field enum values. It is called by the builders before save.
func OperationValidator(o Operation) error {
	switch o {
	case OperationGeneration, OperationEdit, OperationExtension:
		return nil
	default:
		return fmt.Errorf("videotask: invalid enum value for operation field: %q", o)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusCreated is the default value of the Status enum.
const DefaultStatus = StatusCreated

// Status values.
const (
	StatusCreated    Status = "created"
	StatusSubmitting Status = "submitting"
	StatusSubmitted  Status = "submitted"
	StatusQueued     Status = "queued"
	StatusRunning    Status = "running"
	StatusSucceeded  Status = "succeeded"
	StatusFailed     Status = "failed"
	StatusCancelled  Status = "cancelled"
	StatusUnknown    Status = "unknown"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusCreated, StatusSubmitting, StatusSubmitted, StatusQueued, StatusRunning, StatusSucceeded, StatusFailed, StatusCancelled, StatusUnknown:
		return nil
	default:
		return fmt.Errorf("videotask: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the VideoTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByExternalModel orders the results by the external_model field.
func ByExternalModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByIdempotencyKeyHash orders the results by the idempotency_key_hash field.
func ByIdempotencyKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKeyHash, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByProviderSubmissionToken orders the results by the provider_submission_token field.
func ByProviderSubmissionToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderSubmissionToken, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByUpstreamStatus orders the results by the upstream_status field.
func ByUpstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatus, opts...).ToFunc()
}

// ByResultURL orders the results by the result_url field.
func ByResultURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultURL, opts...).ToFunc()
}

// ByResultURLExpiresAt orders the results by the result_url_expires_at field.
func ByResultURLExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultURLExpiresAt, opts...).ToFunc()
}

// ByResultContentType orders the results by the result_content_type field.
func ByResultContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultContentType, opts...).ToFunc()
}

// ByResultDurationSeconds orders the results by the result_duration_seconds field.
func ByResultDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultDurationSeconds, opts...).ToFunc()
}

// ByResultWidth orders the results by the result_width field.
func ByResultWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultWidth, opts...).ToFunc()
}

// ByResultHeight orders the results by the result_height field.
func ByResultHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultHeight, opts...).ToFunc()
}

// ByPricingUnit orders the results by the pricing_unit field.
func ByPricingUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingUnit, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByEstimatedUnits orders the results by the estimated_units field.
func ByEstimatedUnits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedUnits, opts...).ToFunc()
}

// ByEstimatedAmount orders the results by the estimated_amount field.
func ByEstimatedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedAmount, opts...).ToFunc()
}

// ByFrozenAmount orders the results by the frozen_amount field.
func ByFrozenAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozenAmount, opts...).ToFunc()
}

// BySettledAmount orders the results by the settled_amount field.
func BySettledAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByBillingMode orders the results by the billing_mode field.
func ByBillingMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingMode, opts...).ToFunc()
}

// ByBillingStatus orders the results by the billing_status field.
func ByBillingStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingStatus, opts...).ToFunc()
}

// ByBillingReference orders the results by the billing_reference field.
func ByBillingReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingReference, opts...).ToFunc()
}

// BySubmissionAttempts orders the results by the submission_attempts field.
func BySubmissionAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmissionAttempts, opts...).ToFunc()
}

// ByPollAttempts orders the results by the poll_attempts field.
func ByPollAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollAttempts, opts...).ToFunc()
}

// BySettlementAttempts orders the results by the settlement_attempts field.
func BySettlementAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementAttempts, opts...).ToFunc()
}

// ByNextPollAt orders the results by the next_poll_at field.
func ByNextPollAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextPollAt, opts...).ToFunc()
}

// ByLeaseOwner orders the results by the lease_owner field.
func ByLeaseOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseOwner, opts...).ToFunc()
}

// ByLeaseExpiresAt orders the results by the lease_expires_at field.
func ByLeaseExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseExpiresAt, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByLastErrorMessage orders the results by the last_error_message field.
func ByLastErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorMessage, opts...).ToFunc()
}

// ByLastErrorRetryable orders the results by the last_error_retryable field.
func ByLastErrorRetryable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorRetryable, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}
