// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/videotaskevent"
)

// VideoTaskEventCreate is the builder for creating a VideoTaskEvent entity.
type VideoTaskEventCreate struct {
	config
	mutation *VideoTaskEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *VideoTaskEventCreate) SetRequestID(v string) *VideoTaskEventCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *VideoTaskEventCreate) SetEventType(v string) *VideoTaskEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *VideoTaskEventCreate) SetPayload(v json.RawMessage) *VideoTaskEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoTaskEventCreate) SetCreatedAt(v time.Time) *VideoTaskEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoTaskEventCreate) SetNillableCreatedAt(v *time.Time) *VideoTaskEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the VideoTaskEventMutation object of the builder.
func (_c *VideoTaskEventCreate) Mutation() *VideoTaskEventMutation {
	return _c.mutation
}

// Save creates the VideoTaskEvent in the database.
func (_c *VideoTaskEventCreate) Save(ctx context.Context) (*VideoTaskEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoTaskEventCreate) SaveX(ctx context.Context) *VideoTaskEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoTaskEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoTaskEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoTaskEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videotaskevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoTaskEventCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "VideoTaskEvent.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := videotaskevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "VideoTaskEvent.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "VideoTaskEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := videotaskevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "VideoTaskEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoTaskEvent.created_at"`)}
	}
	return nil
}

func (_c *VideoTaskEventCreate) sqlSave(ctx context.Context) (*VideoTaskEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoTaskEventCreate) createSpec() (*VideoTaskEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoTaskEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videotaskevent.Table, sqlgraph.NewFieldSpec(videotaskevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(videotaskevent.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(videotaskevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(videotaskevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videotaskevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoTaskEvent.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoTaskEventUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoTaskEventCreate) OnConflict(opts ...sql.ConflictOption) *VideoTaskEventUpsertOne {
	_c.conflict = opts
	return &VideoTaskEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoTaskEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoTaskEventCreate) OnConflictColumns(columns ...string) *VideoTaskEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoTaskEventUpsertOne{
		create: _c,
	}
}

type (
	// VideoTaskEventUpsertOne is the builder for "upsert"-ing
	//  one VideoTaskEvent node.
	VideoTaskEventUpsertOne struct {
		create *VideoTaskEventCreate
	}

	// VideoTaskEventUpsert is the "OnConflict" setter.
	VideoTaskEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *VideoTaskEventUpsert) SetRequestID(v string) *VideoTaskEventUpsert {
	u.Set(videotaskevent.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *VideoTaskEventUpsert) UpdateRequestID() *VideoTaskEventUpsert {
	u.SetExcluded(videotaskevent.FieldRequestID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *VideoTaskEventUpsert) SetEventType(v string) *VideoTaskEventUpsert {
	u.Set(videotaskevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *VideoTaskEventUpsert) UpdateEventType() *VideoTaskEventUpsert {
	u.SetExcluded(videotaskevent.FieldEventType)
	return u
}

// SetPayload sets the "payload" field.
func (u *VideoTaskEventUpsert) SetPayload(v json.RawMessage) *VideoTaskEventUpsert {
	u.Set(videotaskevent.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *VideoTaskEventUpsert) UpdatePayload() *VideoTaskEventUpsert {
	u.SetExcluded(videotaskevent.FieldPayload)
	return u
}

// ClearPayload clears the value of the "payload" field.
func (u *VideoTaskEventUpsert) ClearPayload() *VideoTaskEventUpsert {
	u.SetNull(videotaskevent.FieldPayload)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoTaskEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoTaskEventUpsertOne) UpdateNewValues() *VideoTaskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videotaskevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoTaskEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoTaskEventUpsertOne) Ignore() *VideoTaskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoTaskEventUpsertOne) DoNothing() *VideoTaskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoTaskEventCreate.OnConflict
// documentation for more info.
func (u *VideoTaskEventUpsertOne) Update(set func(*VideoTaskEventUpsert)) *VideoTaskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoTaskEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *VideoTaskEventUpsertOne) SetRequestID(v string) *VideoTaskEventUpsertOne {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *VideoTaskEventUpsertOne) UpdateRequestID() *VideoTaskEventUpsertOne {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.UpdateRequestID()
	})
}

// SetEventType sets the "event_type" field.
func (u *VideoTaskEventUpsertOne) SetEventType(v string) *VideoTaskEventUpsertOne {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *VideoTaskEventUpsertOne) UpdateEventType() *VideoTaskEventUpsertOne {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.UpdateEventType()
	})
}

// SetPayload sets the "payload" field.
func (u *VideoTaskEventUpsertOne) SetPayload(v json.RawMessage) *VideoTaskEventUpsertOne {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *VideoTaskEventUpsertOne) UpdatePayload() *VideoTaskEventUpsertOne {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *VideoTaskEventUpsertOne) ClearPayload() *VideoTaskEventUpsertOne {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.ClearPayload()
	})
}

// Exec executes the query.
func (u *VideoTaskEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoTaskEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoTaskEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoTaskEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoTaskEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoTaskEventCreateBulk is the builder for creating many VideoTaskEvent entities in bulk.
type VideoTaskEventCreateBulk struct {
	config
	err      error
	builders []*VideoTaskEventCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoTaskEvent entities in the database.
func (_c *VideoTaskEventCreateBulk) Save(ctx context.Context) ([]*VideoTaskEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoTaskEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoTaskEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoTaskEventCreateBulk) SaveX(ctx context.Context) []*VideoTaskEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoTaskEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoTaskEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoTaskEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoTaskEventUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoTaskEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoTaskEventUpsertBulk {
	_c.conflict = opts
	return &VideoTaskEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoTaskEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoTaskEventCreateBulk) OnConflictColumns(columns ...string) *VideoTaskEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoTaskEventUpsertBulk{
		create: _c,
	}
}

// VideoTaskEventUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoTaskEvent nodes.
type VideoTaskEventUpsertBulk struct {
	create *VideoTaskEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoTaskEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoTaskEventUpsertBulk) UpdateNewValues() *VideoTaskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videotaskevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoTaskEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoTaskEventUpsertBulk) Ignore() *VideoTaskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoTaskEventUpsertBulk) DoNothing() *VideoTaskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoTaskEventCreateBulk.OnConflict
// documentation for more info.
func (u *VideoTaskEventUpsertBulk) Update(set func(*VideoTaskEventUpsert)) *VideoTaskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoTaskEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *VideoTaskEventUpsertBulk) SetRequestID(v string) *VideoTaskEventUpsertBulk {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *VideoTaskEventUpsertBulk) UpdateRequestID() *VideoTaskEventUpsertBulk {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.UpdateRequestID()
	})
}

// SetEventType sets the "event_type" field.
func (u *VideoTaskEventUpsertBulk) SetEventType(v string) *VideoTaskEventUpsertBulk {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *VideoTaskEventUpsertBulk) UpdateEventType() *VideoTaskEventUpsertBulk {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.UpdateEventType()
	})
}

// SetPayload sets the "payload" field.
func (u *VideoTaskEventUpsertBulk) SetPayload(v json.RawMessage) *VideoTaskEventUpsertBulk {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *VideoTaskEventUpsertBulk) UpdatePayload() *VideoTaskEventUpsertBulk {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *VideoTaskEventUpsertBulk) ClearPayload() *VideoTaskEventUpsertBulk {
	return u.Update(func(s *VideoTaskEventUpsert) {
		s.ClearPayload()
	})
}

// Exec executes the query.
func (u *VideoTaskEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoTaskEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoTaskEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoTaskEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
