// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTaskUpdate is the builder for updating VideoTask entities.
type VideoTaskUpdate struct {
	config
	hooks    []Hook
	mutation *VideoTaskMutation
}

// Where appends a list predicates to the VideoTaskUpdate builder.
func (_u *VideoTaskUpdate) Where(ps ...predicate.VideoTask) *VideoTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VideoTaskUpdate) SetUserID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUserID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *VideoTaskUpdate) AddUserID(v int64) *VideoTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *VideoTaskUpdate) SetAPIKeyID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableAPIKeyID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *VideoTaskUpdate) AddAPIKeyID(v int64) *VideoTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *VideoTaskUpdate) SetSubscriptionID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableSubscriptionID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *VideoTaskUpdate) AddSubscriptionID(v int64) *VideoTaskUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *VideoTaskUpdate) ClearSubscriptionID() *VideoTaskUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoTaskUpdate) SetGroupID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableGroupID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *VideoTaskUpdate) AddGroupID(v int64) *VideoTaskUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoTaskUpdate) SetAccountID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableAccountID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *VideoTaskUpdate) AddAccountID(v int64) *VideoTaskUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *VideoTaskUpdate) SetPlatform(v videotask.Platform) *VideoTaskUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePlatform(v *videotask.Platform) *VideoTaskUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *VideoTaskUpdate) SetProvider(v videotask.Provider) *VideoTaskUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableProvider(v *videotask.Provider) *VideoTaskUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *VideoTaskUpdate) SetOperation(v videotask.Operation) *VideoTaskUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableOperation(v *videotask.Operation) *VideoTaskUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetExternalModel sets the "external_model" field.
func (_u *VideoTaskUpdate) SetExternalModel(v string) *VideoTaskUpdate {
	_u.mutation.SetExternalModel(v)
	return _u
}

// SetNillableExternalModel sets the "external_model" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableExternalModel(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetExternalModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *VideoTaskUpdate) SetUpstreamModel(v string) *VideoTaskUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamModel(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_u *VideoTaskUpdate) SetIdempotencyKeyHash(v string) *VideoTaskUpdate {
	_u.mutation.SetIdempotencyKeyHash(v)
	return _u
}

// SetNillableIdempotencyKeyHash sets the "idempotency_key_hash" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableIdempotencyKeyHash(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetIdempotencyKeyHash(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *VideoTaskUpdate) SetRequestHash(v string) *VideoTaskUpdate {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableRequestHash(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetProviderSubmissionToken sets the "provider_submission_token" field.
func (_u *VideoTaskUpdate) SetProviderSubmissionToken(v string) *VideoTaskUpdate {
	_u.mutation.SetProviderSubmissionToken(v)
	return _u
}

// SetNillableProviderSubmissionToken sets the "provider_submission_token" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableProviderSubmissionToken(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetProviderSubmissionToken(*v)
	}
	return _u
}

// ClearProviderSubmissionToken clears the value of the "provider_submission_token" field.
func (_u *VideoTaskUpdate) ClearProviderSubmissionToken() *VideoTaskUpdate {
	_u.mutation.ClearProviderSubmissionToken()
	return _u
}

// SetRequestPayload sets the "request_payload" field.
func (_u *VideoTaskUpdate) SetRequestPayload(v json.RawMessage) *VideoTaskUpdate {
	_u.mutation.SetRequestPayload(v)
	return _u
}

// AppendRequestPayload appends value to the "request_payload" field.
func (_u *VideoTaskUpdate) AppendRequestPayload(v json.RawMessage) *VideoTaskUpdate {
	_u.mutation.AppendRequestPayload(v)
	return _u
}

// ClearRequestPayload clears the value of the "request_payload" field.
func (_u *VideoTaskUpdate) ClearRequestPayload() *VideoTaskUpdate {
	_u.mutation.ClearRequestPayload()
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoTaskUpdate) SetStatus(v videotask.Status) *VideoTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableStatus(v *videotask.Status) *VideoTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *VideoTaskUpdate) SetUpstreamTaskID(v string) *VideoTaskUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamTaskID(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *VideoTaskUpdate) ClearUpstreamTaskID() *VideoTaskUpdate {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *VideoTaskUpdate) SetUpstreamStatus(v string) *VideoTaskUpdate {
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamStatus(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (_u *VideoTaskUpdate) ClearUpstreamStatus() *VideoTaskUpdate {
	_u.mutation.ClearUpstreamStatus()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *VideoTaskUpdate) SetResultURL(v string) *VideoTaskUpdate {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResultURL(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *VideoTaskUpdate) ClearResultURL() *VideoTaskUpdate {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultURLExpiresAt sets the "result_url_expires_at" field.
func (_u *VideoTaskUpdate) SetResultURLExpiresAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetResultURLExpiresAt(v)
	return _u
}

// SetNillableResultURLExpiresAt sets the "result_url_expires_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResultURLExpiresAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetResultURLExpiresAt(*v)
	}
	return _u
}

// ClearResultURLExpiresAt clears the value of the "result_url_expires_at" field.
func (_u *VideoTaskUpdate) ClearResultURLExpiresAt() *VideoTaskUpdate {
	_u.mutation.ClearResultURLExpiresAt()
	return _u
}

// SetResultContentType sets the "result_content_type" field.
func (_u *VideoTaskUpdate) SetResultContentType(v string) *VideoTaskUpdate {
	_u.mutation.SetResultContentType(v)
	return _u
}

// SetNillableResultContentType sets the "result_content_type" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResultContentType(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetResultContentType(*v)
	}
	return _u
}

// ClearResultContentType clears the value of the "result_content_type" field.
func (_u *VideoTaskUpdate) ClearResultContentType() *VideoTaskUpdate {
	_u.mutation.ClearResultContentType()
	return _u
}

// SetResultDurationSeconds sets the "result_duration_seconds" field.
func (_u *VideoTaskUpdate) SetResultDurationSeconds(v float64) *VideoTaskUpdate {
	_u.mutation.ResetResultDurationSeconds()
	_u.mutation.SetResultDurationSeconds(v)
	return _u
}

// SetNillableResultDurationSeconds sets the "result_duration_seconds" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResultDurationSeconds(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetResultDurationSeconds(*v)
	}
	return _u
}

// AddResultDurationSeconds adds value to the "result_duration_seconds" field.
func (_u *VideoTaskUpdate) AddResultDurationSeconds(v float64) *VideoTaskUpdate {
	_u.mutation.AddResultDurationSeconds(v)
	return _u
}

// ClearResultDurationSeconds clears the value of the "result_duration_seconds" field.
func (_u *VideoTaskUpdate) ClearResultDurationSeconds() *VideoTaskUpdate {
	_u.mutation.ClearResultDurationSeconds()
	return _u
}

// SetResultWidth sets the "result_width" field.
func (_u *VideoTaskUpdate) SetResultWidth(v int) *VideoTaskUpdate {
	_u.mutation.ResetResultWidth()
	_u.mutation.SetResultWidth(v)
	return _u
}

// SetNillableResultWidth sets the "result_width" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResultWidth(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetResultWidth(*v)
	}
	return _u
}

// AddResultWidth adds value to the "result_width" field.
func (_u *VideoTaskUpdate) AddResultWidth(v int) *VideoTaskUpdate {
	_u.mutation.AddResultWidth(v)
	return _u
}

// ClearResultWidth clears the value of the "result_width" field.
func (_u *VideoTaskUpdate) ClearResultWidth() *VideoTaskUpdate {
	_u.mutation.ClearResultWidth()
	return _u
}

// SetResultHeight sets the "result_height" field.
func (_u *VideoTaskUpdate) SetResultHeight(v int) *VideoTaskUpdate {
	_u.mutation.ResetResultHeight()
	_u.mutation.SetResultHeight(v)
	return _u
}

// SetNillableResultHeight sets the "result_height" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResultHeight(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetResultHeight(*v)
	}
	return _u
}

// AddResultHeight adds value to the "result_height" field.
func (_u *VideoTaskUpdate) AddResultHeight(v int) *VideoTaskUpdate {
	_u.mutation.AddResultHeight(v)
	return _u
}

// ClearResultHeight clears the value of the "result_height" field.
func (_u *VideoTaskUpdate) ClearResultHeight() *VideoTaskUpdate {
	_u.mutation.ClearResultHeight()
	return _u
}

// SetPricingUnit sets the "pricing_unit" field.
func (_u *VideoTaskUpdate) SetPricingUnit(v string) *VideoTaskUpdate {
	_u.mutation.SetPricingUnit(v)
	return _u
}

// SetNillablePricingUnit sets the "pricing_unit" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePricingUnit(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetPricingUnit(*v)
	}
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *VideoTaskUpdate) SetUnitPrice(v float64) *VideoTaskUpdate {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUnitPrice(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *VideoTaskUpdate) AddUnitPrice(v float64) *VideoTaskUpdate {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetUpstreamUnitCost sets the "upstream_unit_cost" field.
func (_u *VideoTaskUpdate) SetUpstreamUnitCost(v float64) *VideoTaskUpdate {
	_u.mutation.ResetUpstreamUnitCost()
	_u.mutation.SetUpstreamUnitCost(v)
	return _u
}

// SetNillableUpstreamUnitCost sets the "upstream_unit_cost" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamUnitCost(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamUnitCost(*v)
	}
	return _u
}

// AddUpstreamUnitCost adds value to the "upstream_unit_cost" field.
func (_u *VideoTaskUpdate) AddUpstreamUnitCost(v float64) *VideoTaskUpdate {
	_u.mutation.AddUpstreamUnitCost(v)
	return _u
}

// ClearUpstreamUnitCost clears the value of the "upstream_unit_cost" field.
func (_u *VideoTaskUpdate) ClearUpstreamUnitCost() *VideoTaskUpdate {
	_u.mutation.ClearUpstreamUnitCost()
	return _u
}

// SetEstimatedUnits sets the "estimated_units" field.
func (_u *VideoTaskUpdate) SetEstimatedUnits(v float64) *VideoTaskUpdate {
	_u.mutation.ResetEstimatedUnits()
	_u.mutation.SetEstimatedUnits(v)
	return _u
}

// SetNillableEstimatedUnits sets the "estimated_units" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableEstimatedUnits(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetEstimatedUnits(*v)
	}
	return _u
}

// AddEstimatedUnits adds value to the "estimated_units" field.
func (_u *VideoTaskUpdate) AddEstimatedUnits(v float64) *VideoTaskUpdate {
	_u.mutation.AddEstimatedUnits(v)
	return _u
}

// SetEstimatedAmount sets the "estimated_amount" field.
func (_u *VideoTaskUpdate) SetEstimatedAmount(v float64) *VideoTaskUpdate {
	_u.mutation.ResetEstimatedAmount()
	_u.mutation.SetEstimatedAmount(v)
	return _u
}

// SetNillableEstimatedAmount sets the "estimated_amount" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableEstimatedAmount(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetEstimatedAmount(*v)
	}
	return _u
}

// AddEstimatedAmount adds value to the "estimated_amount" field.
func (_u *VideoTaskUpdate) AddEstimatedAmount(v float64) *VideoTaskUpdate {
	_u.mutation.AddEstimatedAmount(v)
	return _u
}

// SetFrozenAmount sets the "frozen_amount" field.
func (_u *VideoTaskUpdate) SetFrozenAmount(v float64) *VideoTaskUpdate {
	_u.mutation.ResetFrozenAmount()
	_u.mutation.SetFrozenAmount(v)
	return _u
}

// SetNillableFrozenAmount sets the "frozen_amount" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableFrozenAmount(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetFrozenAmount(*v)
	}
	return _u
}

// AddFrozenAmount adds value to the "frozen_amount" field.
func (_u *VideoTaskUpdate) AddFrozenAmount(v float64) *VideoTaskUpdate {
	_u.mutation.AddFrozenAmount(v)
	return _u
}

// SetSettledAmount sets the "settled_amount" field.
func (_u *VideoTaskUpdate) SetSettledAmount(v float64) *VideoTaskUpdate {
	_u.mutation.ResetSettledAmount()
	_u.mutation.SetSettledAmount(v)
	return _u
}

// SetNillableSettledAmount sets the "settled_amount" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableSettledAmount(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetSettledAmount(*v)
	}
	return _u
}

// AddSettledAmount adds value to the "settled_amount" field.
func (_u *VideoTaskUpdate) AddSettledAmount(v float64) *VideoTaskUpdate {
	_u.mutation.AddSettledAmount(v)
	return _u
}

// ClearSettledAmount clears the value of the "settled_amount" field.
func (_u *VideoTaskUpdate) ClearSettledAmount() *VideoTaskUpdate {
	_u.mutation.ClearSettledAmount()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *VideoTaskUpdate) SetCurrency(v string) *VideoTaskUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableCurrency(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetBillingMode sets the "billing_mode" field.
func (_u *VideoTaskUpdate) SetBillingMode(v string) *VideoTaskUpdate {
	_u.mutation.SetBillingMode(v)
	return _u
}

// SetNillableBillingMode sets the "billing_mode" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableBillingMode(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetBillingMode(*v)
	}
	return _u
}

// SetBillingStatus sets the "billing_status" field.
func (_u *VideoTaskUpdate) SetBillingStatus(v string) *VideoTaskUpdate {
	_u.mutation.SetBillingStatus(v)
	return _u
}

// SetNillableBillingStatus sets the "billing_status" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableBillingStatus(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetBillingStatus(*v)
	}
	return _u
}

// SetBillingReference sets the "billing_reference" field.
func (_u *VideoTaskUpdate) SetBillingReference(v string) *VideoTaskUpdate {
	_u.mutation.SetBillingReference(v)
	return _u
}

// SetNillableBillingReference sets the "billing_reference" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableBillingReference(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetBillingReference(*v)
	}
	return _u
}

// ClearBillingReference clears the value of the "billing_reference" field.
func (_u *VideoTaskUpdate) ClearBillingReference() *VideoTaskUpdate {
	_u.mutation.ClearBillingReference()
	return _u
}

// SetSubmissionAttempts sets the "submission_attempts" field.
func (_u *VideoTaskUpdate) SetSubmissionAttempts(v int) *VideoTaskUpdate {
	_u.mutation.ResetSubmissionAttempts()
	_u.mutation.SetSubmissionAttempts(v)
	return _u
}

// SetNillableSubmissionAttempts sets the "submission_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableSubmissionAttempts(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetSubmissionAttempts(*v)
	}
	return _u
}

// AddSubmissionAttempts adds value to the "submission_attempts" field.
func (_u *VideoTaskUpdate) AddSubmissionAttempts(v int) *VideoTaskUpdate {
	_u.mutation.AddSubmissionAttempts(v)
	return _u
}

// SetPollAttempts sets the "poll_attempts" field.
func (_u *VideoTaskUpdate) SetPollAttempts(v int) *VideoTaskUpdate {
	_u.mutation.ResetPollAttempts()
	_u.mutation.SetPollAttempts(v)
	return _u
}

// SetNillablePollAttempts sets the "poll_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePollAttempts(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetPollAttempts(*v)
	}
	return _u
}

// AddPollAttempts adds value to the "poll_attempts" field.
func (_u *VideoTaskUpdate) AddPollAttempts(v int) *VideoTaskUpdate {
	_u.mutation.AddPollAttempts(v)
	return _u
}

// SetSettlementAttempts sets the "settlement_attempts" field.
func (_u *VideoTaskUpdate) SetSettlementAttempts(v int) *VideoTaskUpdate {
	_u.mutation.ResetSettlementAttempts()
	_u.mutation.SetSettlementAttempts(v)
	return _u
}

// SetNillableSettlementAttempts sets the "settlement_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableSettlementAttempts(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetSettlementAttempts(*v)
	}
	return _u
}

// AddSettlementAttempts adds value to the "settlement_attempts" field.
func (_u *VideoTaskUpdate) AddSettlementAttempts(v int) *VideoTaskUpdate {
	_u.mutation.AddSettlementAttempts(v)
	return _u
}

// SetNextPollAt sets the "next_poll_at" field.
func (_u *VideoTaskUpdate) SetNextPollAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetNextPollAt(v)
	return _u
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableNextPollAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetNextPollAt(*v)
	}
	return _u
}

// ClearNextPollAt clears the value of the "next_poll_at" field.
func (_u *VideoTaskUpdate) ClearNextPollAt() *VideoTaskUpdate {
	_u.mutation.ClearNextPollAt()
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *VideoTaskUpdate) SetLeaseOwner(v string) *VideoTaskUpdate {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLeaseOwner(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *VideoTaskUpdate) ClearLeaseOwner() *VideoTaskUpdate {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *VideoTaskUpdate) SetLeaseExpiresAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLeaseExpiresAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *VideoTaskUpdate) ClearLeaseExpiresAt() *VideoTaskUpdate {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *VideoTaskUpdate) SetLastErrorCode(v string) *VideoTaskUpdate {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLastErrorCode(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *VideoTaskUpdate) ClearLastErrorCode() *VideoTaskUpdate {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *VideoTaskUpdate) SetLastErrorMessage(v string) *VideoTaskUpdate {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLastErrorMessage(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *VideoTaskUpdate) ClearLastErrorMessage() *VideoTaskUpdate {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetLastErrorRetryable sets the "last_error_retryable" field.
func (_u *VideoTaskUpdate) SetLastErrorRetryable(v bool) *VideoTaskUpdate {
	_u.mutation.SetLastErrorRetryable(v)
	return _u
}

// SetNillableLastErrorRetryable sets the "last_error_retryable" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLastErrorRetryable(v *bool) *VideoTaskUpdate {
	if v != nil {
		_u.SetLastErrorRetryable(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *VideoTaskUpdate) SetVersion(v int64) *VideoTaskUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableVersion(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *VideoTaskUpdate) AddVersion(v int64) *VideoTaskUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoTaskUpdate) SetUpdatedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *VideoTaskUpdate) SetSubmittedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableSubmittedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *VideoTaskUpdate) ClearSubmittedAt() *VideoTaskUpdate {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *VideoTaskUpdate) SetStartedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableStartedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *VideoTaskUpdate) ClearStartedAt() *VideoTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *VideoTaskUpdate) SetFinishedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableFinishedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *VideoTaskUpdate) ClearFinishedAt() *VideoTaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *VideoTaskUpdate) SetSettledAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableSettledAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *VideoTaskUpdate) ClearSettledAt() *VideoTaskUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_u *VideoTaskUpdate) Mutation() *VideoTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := videotask.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "VideoTask.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := videotask.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "VideoTask.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := videotask.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "VideoTask.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalModel(); ok {
		if err := videotask.ExternalModelValidator(v); err != nil {
			return &ValidationError{Name: "external_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.external_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := videotask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKeyHash(); ok {
		if err := videotask.IdempotencyKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.idempotency_key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := videotask.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.request_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderSubmissionToken(); ok {
		if err := videotask.ProviderSubmissionTokenValidator(v); err != nil {
			return &ValidationError{Name: "provider_submission_token", err: fmt.Errorf(`ent: validator failed for field "VideoTask.provider_submission_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamStatus(); ok {
		if err := videotask.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultContentType(); ok {
		if err := videotask.ResultContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "result_content_type", err: fmt.Errorf(`ent: validator failed for field "VideoTask.result_content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PricingUnit(); ok {
		if err := videotask.PricingUnitValidator(v); err != nil {
			return &ValidationError{Name: "pricing_unit", err: fmt.Errorf(`ent: validator failed for field "VideoTask.pricing_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := videotask.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "VideoTask.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingMode(); ok {
		if err := videotask.BillingModeValidator(v); err != nil {
			return &ValidationError{Name: "billing_mode", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingStatus(); ok {
		if err := videotask.BillingStatusValidator(v); err != nil {
			return &ValidationError{Name: "billing_status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingReference(); ok {
		if err := videotask.BillingReferenceValidator(v); err != nil {
			return &ValidationError{Name: "billing_reference", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_reference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := videotask.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "VideoTask.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := videotask.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "VideoTask.last_error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotask.Table, videotask.Columns, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(videotask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(videotask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(videotask.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(videotask.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(videotask.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(videotask.FieldOperation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExternalModel(); ok {
		_spec.SetField(videotask.FieldExternalModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(videotask.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(videotask.FieldIdempotencyKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(videotask.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSubmissionToken(); ok {
		_spec.SetField(videotask.FieldProviderSubmissionToken, field.TypeString, value)
	}
	if _u.mutation.ProviderSubmissionTokenCleared() {
		_spec.ClearField(videotask.FieldProviderSubmissionToken, field.TypeString)
	}
	if value, ok := _u.mutation.RequestPayload(); ok {
		_spec.SetField(videotask.FieldRequestPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, videotask.FieldRequestPayload, value)
		})
	}
	if _u.mutation.RequestPayloadCleared() {
		_spec.ClearField(videotask.FieldRequestPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(videotask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(videotask.FieldUpstreamStatus, field.TypeString, value)
	}
	if _u.mutation.UpstreamStatusCleared() {
		_spec.ClearField(videotask.FieldUpstreamStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(videotask.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(videotask.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultURLExpiresAt(); ok {
		_spec.SetField(videotask.FieldResultURLExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ResultURLExpiresAtCleared() {
		_spec.ClearField(videotask.FieldResultURLExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResultContentType(); ok {
		_spec.SetField(videotask.FieldResultContentType, field.TypeString, value)
	}
	if _u.mutation.ResultContentTypeCleared() {
		_spec.ClearField(videotask.FieldResultContentType, field.TypeString)
	}
	if value, ok := _u.mutation.ResultDurationSeconds(); ok {
		_spec.SetField(videotask.FieldResultDurationSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedResultDurationSeconds(); ok {
		_spec.AddField(videotask.FieldResultDurationSeconds, field.TypeFloat64, value)
	}
	if _u.mutation.ResultDurationSecondsCleared() {
		_spec.ClearField(videotask.FieldResultDurationSeconds, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ResultWidth(); ok {
		_spec.SetField(videotask.FieldResultWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultWidth(); ok {
		_spec.AddField(videotask.FieldResultWidth, field.TypeInt, value)
	}
	if _u.mutation.ResultWidthCleared() {
		_spec.ClearField(videotask.FieldResultWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.ResultHeight(); ok {
		_spec.SetField(videotask.FieldResultHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultHeight(); ok {
		_spec.AddField(videotask.FieldResultHeight, field.TypeInt, value)
	}
	if _u.mutation.ResultHeightCleared() {
		_spec.ClearField(videotask.FieldResultHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.PricingUnit(); ok {
		_spec.SetField(videotask.FieldPricingUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(videotask.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(videotask.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpstreamUnitCost(); ok {
		_spec.SetField(videotask.FieldUpstreamUnitCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamUnitCost(); ok {
		_spec.AddField(videotask.FieldUpstreamUnitCost, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamUnitCostCleared() {
		_spec.ClearField(videotask.FieldUpstreamUnitCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.EstimatedUnits(); ok {
		_spec.SetField(videotask.FieldEstimatedUnits, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedUnits(); ok {
		_spec.AddField(videotask.FieldEstimatedUnits, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EstimatedAmount(); ok {
		_spec.SetField(videotask.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedAmount(); ok {
		_spec.AddField(videotask.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrozenAmount(); ok {
		_spec.SetField(videotask.FieldFrozenAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenAmount(); ok {
		_spec.AddField(videotask.FieldFrozenAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SettledAmount(); ok {
		_spec.SetField(videotask.FieldSettledAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledAmount(); ok {
		_spec.AddField(videotask.FieldSettledAmount, field.TypeFloat64, value)
	}
	if _u.mutation.SettledAmountCleared() {
		_spec.ClearField(videotask.FieldSettledAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(videotask.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingMode(); ok {
		_spec.SetField(videotask.FieldBillingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingStatus(); ok {
		_spec.SetField(videotask.FieldBillingStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingReference(); ok {
		_spec.SetField(videotask.FieldBillingReference, field.TypeString, value)
	}
	if _u.mutation.BillingReferenceCleared() {
		_spec.ClearField(videotask.FieldBillingReference, field.TypeString)
	}
	if value, ok := _u.mutation.SubmissionAttempts(); ok {
		_spec.SetField(videotask.FieldSubmissionAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSubmissionAttempts(); ok {
		_spec.AddField(videotask.FieldSubmissionAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PollAttempts(); ok {
		_spec.SetField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollAttempts(); ok {
		_spec.AddField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettlementAttempts(); ok {
		_spec.SetField(videotask.FieldSettlementAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettlementAttempts(); ok {
		_spec.AddField(videotask.FieldSettlementAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextPollAt(); ok {
		_spec.SetField(videotask.FieldNextPollAt, field.TypeTime, value)
	}
	if _u.mutation.NextPollAtCleared() {
		_spec.ClearField(videotask.FieldNextPollAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(videotask.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(videotask.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(videotask.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(videotask.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(videotask.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(videotask.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(videotask.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(videotask.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorRetryable(); ok {
		_spec.SetField(videotask.FieldLastErrorRetryable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(videotask.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(videotask.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(videotask.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(videotask.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(videotask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(videotask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(videotask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(videotask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(videotask.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(videotask.FieldSettledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoTaskUpdateOne is the builder for updating a single VideoTask entity.
type VideoTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoTaskMutation
}

// SetUserID sets the "user_id" field.
func (_u *VideoTaskUpdateOne) SetUserID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUserID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *VideoTaskUpdateOne) AddUserID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *VideoTaskUpdateOne) SetAPIKeyID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableAPIKeyID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *VideoTaskUpdateOne) AddAPIKeyID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *VideoTaskUpdateOne) SetSubscriptionID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableSubscriptionID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *VideoTaskUpdateOne) AddSubscriptionID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *VideoTaskUpdateOne) ClearSubscriptionID() *VideoTaskUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoTaskUpdateOne) SetGroupID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableGroupID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *VideoTaskUpdateOne) AddGroupID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoTaskUpdateOne) SetAccountID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableAccountID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *VideoTaskUpdateOne) AddAccountID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *VideoTaskUpdateOne) SetPlatform(v videotask.Platform) *VideoTaskUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePlatform(v *videotask.Platform) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *VideoTaskUpdateOne) SetProvider(v videotask.Provider) *VideoTaskUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableProvider(v *videotask.Provider) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *VideoTaskUpdateOne) SetOperation(v videotask.Operation) *VideoTaskUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableOperation(v *videotask.Operation) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetExternalModel sets the "external_model" field.
func (_u *VideoTaskUpdateOne) SetExternalModel(v string) *VideoTaskUpdateOne {
	_u.mutation.SetExternalModel(v)
	return _u
}

// SetNillableExternalModel sets the "external_model" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableExternalModel(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetExternalModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *VideoTaskUpdateOne) SetUpstreamModel(v string) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamModel(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_u *VideoTaskUpdateOne) SetIdempotencyKeyHash(v string) *VideoTaskUpdateOne {
	_u.mutation.SetIdempotencyKeyHash(v)
	return _u
}

// SetNillableIdempotencyKeyHash sets the "idempotency_key_hash" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableIdempotencyKeyHash(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetIdempotencyKeyHash(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *VideoTaskUpdateOne) SetRequestHash(v string) *VideoTaskUpdateOne {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableRequestHash(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetProviderSubmissionToken sets the "provider_submission_token" field.
func (_u *VideoTaskUpdateOne) SetProviderSubmissionToken(v string) *VideoTaskUpdateOne {
	_u.mutation.SetProviderSubmissionToken(v)
	return _u
}

// SetNillableProviderSubmissionToken sets the "provider_submission_token" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableProviderSubmissionToken(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetProviderSubmissionToken(*v)
	}
	return _u
}

// ClearProviderSubmissionToken clears the value of the "provider_submission_token" field.
func (_u *VideoTaskUpdateOne) ClearProviderSubmissionToken() *VideoTaskUpdateOne {
	_u.mutation.ClearProviderSubmissionToken()
	return _u
}

// SetRequestPayload sets the "request_payload" field.
func (_u *VideoTaskUpdateOne) SetRequestPayload(v json.RawMessage) *VideoTaskUpdateOne {
	_u.mutation.SetRequestPayload(v)
	return _u
}

// AppendRequestPayload appends value to the "request_payload" field.
func (_u *VideoTaskUpdateOne) AppendRequestPayload(v json.RawMessage) *VideoTaskUpdateOne {
	_u.mutation.AppendRequestPayload(v)
	return _u
}

// ClearRequestPayload clears the value of the "request_payload" field.
func (_u *VideoTaskUpdateOne) ClearRequestPayload() *VideoTaskUpdateOne {
	_u.mutation.ClearRequestPayload()
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoTaskUpdateOne) SetStatus(v videotask.Status) *VideoTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableStatus(v *videotask.Status) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *VideoTaskUpdateOne) SetUpstreamTaskID(v string) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamTaskID(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *VideoTaskUpdateOne) ClearUpstreamTaskID() *VideoTaskUpdateOne {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *VideoTaskUpdateOne) SetUpstreamStatus(v string) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamStatus(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (_u *VideoTaskUpdateOne) ClearUpstreamStatus() *VideoTaskUpdateOne {
	_u.mutation.ClearUpstreamStatus()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *VideoTaskUpdateOne) SetResultURL(v string) *VideoTaskUpdateOne {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResultURL(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *VideoTaskUpdateOne) ClearResultURL() *VideoTaskUpdateOne {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultURLExpiresAt sets the "result_url_expires_at" field.
func (_u *VideoTaskUpdateOne) SetResultURLExpiresAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetResultURLExpiresAt(v)
	return _u
}

// SetNillableResultURLExpiresAt sets the "result_url_expires_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResultURLExpiresAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResultURLExpiresAt(*v)
	}
	return _u
}

// ClearResultURLExpiresAt clears the value of the "result_url_expires_at" field.
func (_u *VideoTaskUpdateOne) ClearResultURLExpiresAt() *VideoTaskUpdateOne {
	_u.mutation.ClearResultURLExpiresAt()
	return _u
}

// SetResultContentType sets the "result_content_type" field.
func (_u *VideoTaskUpdateOne) SetResultContentType(v string) *VideoTaskUpdateOne {
	_u.mutation.SetResultContentType(v)
	return _u
}

// SetNillableResultContentType sets the "result_content_type" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResultContentType(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResultContentType(*v)
	}
	return _u
}

// ClearResultContentType clears the value of the "result_content_type" field.
func (_u *VideoTaskUpdateOne) ClearResultContentType() *VideoTaskUpdateOne {
	_u.mutation.ClearResultContentType()
	return _u
}

// SetResultDurationSeconds sets the "result_duration_seconds" field.
func (_u *VideoTaskUpdateOne) SetResultDurationSeconds(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetResultDurationSeconds()
	_u.mutation.SetResultDurationSeconds(v)
	return _u
}

// SetNillableResultDurationSeconds sets the "result_duration_seconds" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResultDurationSeconds(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResultDurationSeconds(*v)
	}
	return _u
}

// AddResultDurationSeconds adds value to the "result_duration_seconds" field.
func (_u *VideoTaskUpdateOne) AddResultDurationSeconds(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddResultDurationSeconds(v)
	return _u
}

// ClearResultDurationSeconds clears the value of the "result_duration_seconds" field.
func (_u *VideoTaskUpdateOne) ClearResultDurationSeconds() *VideoTaskUpdateOne {
	_u.mutation.ClearResultDurationSeconds()
	return _u
}

// SetResultWidth sets the "result_width" field.
func (_u *VideoTaskUpdateOne) SetResultWidth(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetResultWidth()
	_u.mutation.SetResultWidth(v)
	return _u
}

// SetNillableResultWidth sets the "result_width" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResultWidth(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResultWidth(*v)
	}
	return _u
}

// AddResultWidth adds value to the "result_width" field.
func (_u *VideoTaskUpdateOne) AddResultWidth(v int) *VideoTaskUpdateOne {
	_u.mutation.AddResultWidth(v)
	return _u
}

// ClearResultWidth clears the value of the "result_width" field.
func (_u *VideoTaskUpdateOne) ClearResultWidth() *VideoTaskUpdateOne {
	_u.mutation.ClearResultWidth()
	return _u
}

// SetResultHeight sets the "result_height" field.
func (_u *VideoTaskUpdateOne) SetResultHeight(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetResultHeight()
	_u.mutation.SetResultHeight(v)
	return _u
}

// SetNillableResultHeight sets the "result_height" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResultHeight(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResultHeight(*v)
	}
	return _u
}

// AddResultHeight adds value to the "result_height" field.
func (_u *VideoTaskUpdateOne) AddResultHeight(v int) *VideoTaskUpdateOne {
	_u.mutation.AddResultHeight(v)
	return _u
}

// ClearResultHeight clears the value of the "result_height" field.
func (_u *VideoTaskUpdateOne) ClearResultHeight() *VideoTaskUpdateOne {
	_u.mutation.ClearResultHeight()
	return _u
}

// SetPricingUnit sets the "pricing_unit" field.
func (_u *VideoTaskUpdateOne) SetPricingUnit(v string) *VideoTaskUpdateOne {
	_u.mutation.SetPricingUnit(v)
	return _u
}

// SetNillablePricingUnit sets the "pricing_unit" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePricingUnit(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPricingUnit(*v)
	}
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *VideoTaskUpdateOne) SetUnitPrice(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUnitPrice(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *VideoTaskUpdateOne) AddUnitPrice(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetUpstreamUnitCost sets the "upstream_unit_cost" field.
func (_u *VideoTaskUpdateOne) SetUpstreamUnitCost(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetUpstreamUnitCost()
	_u.mutation.SetUpstreamUnitCost(v)
	return _u
}

// SetNillableUpstreamUnitCost sets the "upstream_unit_cost" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamUnitCost(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamUnitCost(*v)
	}
	return _u
}

// AddUpstreamUnitCost adds value to the "upstream_unit_cost" field.
func (_u *VideoTaskUpdateOne) AddUpstreamUnitCost(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddUpstreamUnitCost(v)
	return _u
}

// ClearUpstreamUnitCost clears the value of the "upstream_unit_cost" field.
func (_u *VideoTaskUpdateOne) ClearUpstreamUnitCost() *VideoTaskUpdateOne {
	_u.mutation.ClearUpstreamUnitCost()
	return _u
}

// SetEstimatedUnits sets the "estimated_units" field.
func (_u *VideoTaskUpdateOne) SetEstimatedUnits(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetEstimatedUnits()
	_u.mutation.SetEstimatedUnits(v)
	return _u
}

// SetNillableEstimatedUnits sets the "estimated_units" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableEstimatedUnits(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetEstimatedUnits(*v)
	}
	return _u
}

// AddEstimatedUnits adds value to the "estimated_units" field.
func (_u *VideoTaskUpdateOne) AddEstimatedUnits(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddEstimatedUnits(v)
	return _u
}

// SetEstimatedAmount sets the "estimated_amount" field.
func (_u *VideoTaskUpdateOne) SetEstimatedAmount(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetEstimatedAmount()
	_u.mutation.SetEstimatedAmount(v)
	return _u
}

// SetNillableEstimatedAmount sets the "estimated_amount" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableEstimatedAmount(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetEstimatedAmount(*v)
	}
	return _u
}

// AddEstimatedAmount adds value to the "estimated_amount" field.
func (_u *VideoTaskUpdateOne) AddEstimatedAmount(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddEstimatedAmount(v)
	return _u
}

// SetFrozenAmount sets the "frozen_amount" field.
func (_u *VideoTaskUpdateOne) SetFrozenAmount(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetFrozenAmount()
	_u.mutation.SetFrozenAmount(v)
	return _u
}

// SetNillableFrozenAmount sets the "frozen_amount" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableFrozenAmount(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetFrozenAmount(*v)
	}
	return _u
}

// AddFrozenAmount adds value to the "frozen_amount" field.
func (_u *VideoTaskUpdateOne) AddFrozenAmount(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddFrozenAmount(v)
	return _u
}

// SetSettledAmount sets the "settled_amount" field.
func (_u *VideoTaskUpdateOne) SetSettledAmount(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetSettledAmount()
	_u.mutation.SetSettledAmount(v)
	return _u
}

// SetNillableSettledAmount sets the "settled_amount" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableSettledAmount(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetSettledAmount(*v)
	}
	return _u
}

// AddSettledAmount adds value to the "settled_amount" field.
func (_u *VideoTaskUpdateOne) AddSettledAmount(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddSettledAmount(v)
	return _u
}

// ClearSettledAmount clears the value of the "settled_amount" field.
func (_u *VideoTaskUpdateOne) ClearSettledAmount() *VideoTaskUpdateOne {
	_u.mutation.ClearSettledAmount()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *VideoTaskUpdateOne) SetCurrency(v string) *VideoTaskUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableCurrency(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetBillingMode sets the "billing_mode" field.
func (_u *VideoTaskUpdateOne) SetBillingMode(v string) *VideoTaskUpdateOne {
	_u.mutation.SetBillingMode(v)
	return _u
}

// SetNillableBillingMode sets the "billing_mode" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableBillingMode(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetBillingMode(*v)
	}
	return _u
}

// SetBillingStatus sets the "billing_status" field.
func (_u *VideoTaskUpdateOne) SetBillingStatus(v string) *VideoTaskUpdateOne {
	_u.mutation.SetBillingStatus(v)
	return _u
}

// SetNillableBillingStatus sets the "billing_status" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableBillingStatus(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetBillingStatus(*v)
	}
	return _u
}

// SetBillingReference sets the "billing_reference" field.
func (_u *VideoTaskUpdateOne) SetBillingReference(v string) *VideoTaskUpdateOne {
	_u.mutation.SetBillingReference(v)
	return _u
}

// SetNillableBillingReference sets the "billing_reference" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableBillingReference(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetBillingReference(*v)
	}
	return _u
}

// ClearBillingReference clears the value of the "billing_reference" field.
func (_u *VideoTaskUpdateOne) ClearBillingReference() *VideoTaskUpdateOne {
	_u.mutation.ClearBillingReference()
	return _u
}

// SetSubmissionAttempts sets the "submission_attempts" field.
func (_u *VideoTaskUpdateOne) SetSubmissionAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetSubmissionAttempts()
	_u.mutation.SetSubmissionAttempts(v)
	return _u
}

// SetNillableSubmissionAttempts sets the "submission_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableSubmissionAttempts(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetSubmissionAttempts(*v)
	}
	return _u
}

// AddSubmissionAttempts adds value to the "submission_attempts" field.
func (_u *VideoTaskUpdateOne) AddSubmissionAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.AddSubmissionAttempts(v)
	return _u
}

// SetPollAttempts sets the "poll_attempts" field.
func (_u *VideoTaskUpdateOne) SetPollAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetPollAttempts()
	_u.mutation.SetPollAttempts(v)
	return _u
}

// SetNillablePollAttempts sets the "poll_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePollAttempts(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPollAttempts(*v)
	}
	return _u
}

// AddPollAttempts adds value to the "poll_attempts" field.
func (_u *VideoTaskUpdateOne) AddPollAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.AddPollAttempts(v)
	return _u
}

// SetSettlementAttempts sets the "settlement_attempts" field.
func (_u *VideoTaskUpdateOne) SetSettlementAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetSettlementAttempts()
	_u.mutation.SetSettlementAttempts(v)
	return _u
}

// SetNillableSettlementAttempts sets the "settlement_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableSettlementAttempts(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetSettlementAttempts(*v)
	}
	return _u
}

// AddSettlementAttempts adds value to the "settlement_attempts" field.
func (_u *VideoTaskUpdateOne) AddSettlementAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.AddSettlementAttempts(v)
	return _u
}

// SetNextPollAt sets the "next_poll_at" field.
func (_u *VideoTaskUpdateOne) SetNextPollAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetNextPollAt(v)
	return _u
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableNextPollAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetNextPollAt(*v)
	}
	return _u
}

// ClearNextPollAt clears the value of the "next_poll_at" field.
func (_u *VideoTaskUpdateOne) ClearNextPollAt() *VideoTaskUpdateOne {
	_u.mutation.ClearNextPollAt()
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *VideoTaskUpdateOne) SetLeaseOwner(v string) *VideoTaskUpdateOne {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLeaseOwner(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *VideoTaskUpdateOne) ClearLeaseOwner() *VideoTaskUpdateOne {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *VideoTaskUpdateOne) SetLeaseExpiresAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLeaseExpiresAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *VideoTaskUpdateOne) ClearLeaseExpiresAt() *VideoTaskUpdateOne {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *VideoTaskUpdateOne) SetLastErrorCode(v string) *VideoTaskUpdateOne {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLastErrorCode(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *VideoTaskUpdateOne) ClearLastErrorCode() *VideoTaskUpdateOne {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *VideoTaskUpdateOne) SetLastErrorMessage(v string) *VideoTaskUpdateOne {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLastErrorMessage(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *VideoTaskUpdateOne) ClearLastErrorMessage() *VideoTaskUpdateOne {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetLastErrorRetryable sets the "last_error_retryable" field.
func (_u *VideoTaskUpdateOne) SetLastErrorRetryable(v bool) *VideoTaskUpdateOne {
	_u.mutation.SetLastErrorRetryable(v)
	return _u
}

// SetNillableLastErrorRetryable sets the "last_error_retryable" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLastErrorRetryable(v *bool) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLastErrorRetryable(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *VideoTaskUpdateOne) SetVersion(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableVersion(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *VideoTaskUpdateOne) AddVersion(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoTaskUpdateOne) SetUpdatedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *VideoTaskUpdateOne) SetSubmittedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableSubmittedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *VideoTaskUpdateOne) ClearSubmittedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *VideoTaskUpdateOne) SetStartedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableStartedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *VideoTaskUpdateOne) ClearStartedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *VideoTaskUpdateOne) SetFinishedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableFinishedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *VideoTaskUpdateOne) ClearFinishedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *VideoTaskUpdateOne) SetSettledAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableSettledAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *VideoTaskUpdateOne) ClearSettledAt() *VideoTaskUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_u *VideoTaskUpdateOne) Mutation() *VideoTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the VideoTaskUpdate builder.
func (_u *VideoTaskUpdateOne) Where(ps ...predicate.VideoTask) *VideoTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoTaskUpdateOne) Select(field string, fields ...string) *VideoTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoTask entity.
func (_u *VideoTaskUpdateOne) Save(ctx context.Context) (*VideoTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskUpdateOne) SaveX(ctx context.Context) *VideoTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := videotask.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "VideoTask.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := videotask.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "VideoTask.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := videotask.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "VideoTask.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalModel(); ok {
		if err := videotask.ExternalModelValidator(v); err != nil {
			return &ValidationError{Name: "external_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.external_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := videotask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKeyHash(); ok {
		if err := videotask.IdempotencyKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.idempotency_key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := videotask.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.request_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderSubmissionToken(); ok {
		if err := videotask.ProviderSubmissionTokenValidator(v); err != nil {
			return &ValidationError{Name: "provider_submission_token", err: fmt.Errorf(`ent: validator failed for field "VideoTask.provider_submission_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamStatus(); ok {
		if err := videotask.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultContentType(); ok {
		if err := videotask.ResultContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "result_content_type", err: fmt.Errorf(`ent: validator failed for field "VideoTask.result_content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PricingUnit(); ok {
		if err := videotask.PricingUnitValidator(v); err != nil {
			return &ValidationError{Name: "pricing_unit", err: fmt.Errorf(`ent: validator failed for field "VideoTask.pricing_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := videotask.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "VideoTask.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingMode(); ok {
		if err := videotask.BillingModeValidator(v); err != nil {
			return &ValidationError{Name: "billing_mode", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingStatus(); ok {
		if err := videotask.BillingStatusValidator(v); err != nil {
			return &ValidationError{Name: "billing_status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingReference(); ok {
		if err := videotask.BillingReferenceValidator(v); err != nil {
			return &ValidationError{Name: "billing_reference", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_reference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := videotask.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "VideoTask.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := videotask.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "VideoTask.last_error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoTaskUpdateOne) sqlSave(ctx context.Context) (_node *VideoTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotask.Table, videotask.Columns, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videotask.FieldID)
		for _, f := range fields {
			if !videotask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videotask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(videotask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(videotask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(videotask.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(videotask.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(videotask.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(videotask.FieldOperation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExternalModel(); ok {
		_spec.SetField(videotask.FieldExternalModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(videotask.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(videotask.FieldIdempotencyKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(videotask.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSubmissionToken(); ok {
		_spec.SetField(videotask.FieldProviderSubmissionToken, field.TypeString, value)
	}
	if _u.mutation.ProviderSubmissionTokenCleared() {
		_spec.ClearField(videotask.FieldProviderSubmissionToken, field.TypeString)
	}
	if value, ok := _u.mutation.RequestPayload(); ok {
		_spec.SetField(videotask.FieldRequestPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, videotask.FieldRequestPayload, value)
		})
	}
	if _u.mutation.RequestPayloadCleared() {
		_spec.ClearField(videotask.FieldRequestPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(videotask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(videotask.FieldUpstreamStatus, field.TypeString, value)
	}
	if _u.mutation.UpstreamStatusCleared() {
		_spec.ClearField(videotask.FieldUpstreamStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(videotask.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(videotask.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultURLExpiresAt(); ok {
		_spec.SetField(videotask.FieldResultURLExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ResultURLExpiresAtCleared() {
		_spec.ClearField(videotask.FieldResultURLExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResultContentType(); ok {
		_spec.SetField(videotask.FieldResultContentType, field.TypeString, value)
	}
	if _u.mutation.ResultContentTypeCleared() {
		_spec.ClearField(videotask.FieldResultContentType, field.TypeString)
	}
	if value, ok := _u.mutation.ResultDurationSeconds(); ok {
		_spec.SetField(videotask.FieldResultDurationSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedResultDurationSeconds(); ok {
		_spec.AddField(videotask.FieldResultDurationSeconds, field.TypeFloat64, value)
	}
	if _u.mutation.ResultDurationSecondsCleared() {
		_spec.ClearField(videotask.FieldResultDurationSeconds, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ResultWidth(); ok {
		_spec.SetField(videotask.FieldResultWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultWidth(); ok {
		_spec.AddField(videotask.FieldResultWidth, field.TypeInt, value)
	}
	if _u.mutation.ResultWidthCleared() {
		_spec.ClearField(videotask.FieldResultWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.ResultHeight(); ok {
		_spec.SetField(videotask.FieldResultHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultHeight(); ok {
		_spec.AddField(videotask.FieldResultHeight, field.TypeInt, value)
	}
	if _u.mutation.ResultHeightCleared() {
		_spec.ClearField(videotask.FieldResultHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.PricingUnit(); ok {
		_spec.SetField(videotask.FieldPricingUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(videotask.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(videotask.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpstreamUnitCost(); ok {
		_spec.SetField(videotask.FieldUpstreamUnitCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamUnitCost(); ok {
		_spec.AddField(videotask.FieldUpstreamUnitCost, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamUnitCostCleared() {
		_spec.ClearField(videotask.FieldUpstreamUnitCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.EstimatedUnits(); ok {
		_spec.SetField(videotask.FieldEstimatedUnits, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedUnits(); ok {
		_spec.AddField(videotask.FieldEstimatedUnits, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EstimatedAmount(); ok {
		_spec.SetField(videotask.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedAmount(); ok {
		_spec.AddField(videotask.FieldEstimatedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrozenAmount(); ok {
		_spec.SetField(videotask.FieldFrozenAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenAmount(); ok {
		_spec.AddField(videotask.FieldFrozenAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SettledAmount(); ok {
		_spec.SetField(videotask.FieldSettledAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledAmount(); ok {
		_spec.AddField(videotask.FieldSettledAmount, field.TypeFloat64, value)
	}
	if _u.mutation.SettledAmountCleared() {
		_spec.ClearField(videotask.FieldSettledAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(videotask.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingMode(); ok {
		_spec.SetField(videotask.FieldBillingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingStatus(); ok {
		_spec.SetField(videotask.FieldBillingStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingReference(); ok {
		_spec.SetField(videotask.FieldBillingReference, field.TypeString, value)
	}
	if _u.mutation.BillingReferenceCleared() {
		_spec.ClearField(videotask.FieldBillingReference, field.TypeString)
	}
	if value, ok := _u.mutation.SubmissionAttempts(); ok {
		_spec.SetField(videotask.FieldSubmissionAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSubmissionAttempts(); ok {
		_spec.AddField(videotask.FieldSubmissionAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PollAttempts(); ok {
		_spec.SetField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollAttempts(); ok {
		_spec.AddField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettlementAttempts(); ok {
		_spec.SetField(videotask.FieldSettlementAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettlementAttempts(); ok {
		_spec.AddField(videotask.FieldSettlementAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextPollAt(); ok {
		_spec.SetField(videotask.FieldNextPollAt, field.TypeTime, value)
	}
	if _u.mutation.NextPollAtCleared() {
		_spec.ClearField(videotask.FieldNextPollAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(videotask.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(videotask.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(videotask.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(videotask.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(videotask.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(videotask.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(videotask.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(videotask.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorRetryable(); ok {
		_spec.SetField(videotask.FieldLastErrorRetryable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(videotask.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(videotask.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(videotask.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(videotask.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(videotask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(videotask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(videotask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(videotask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(videotask.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(videotask.FieldSettledAt, field.TypeTime)
	}
	_node = &VideoTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
