// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/videopricingrule"
)

// VideoPricingRuleCreate is the builder for creating a VideoPricingRule entity.
type VideoPricingRuleCreate struct {
	config
	mutation *VideoPricingRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *VideoPricingRuleCreate) SetGroupID(v int64) *VideoPricingRuleCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetExternalModel sets the "external_model" field.
func (_c *VideoPricingRuleCreate) SetExternalModel(v string) *VideoPricingRuleCreate {
	_c.mutation.SetExternalModel(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *VideoPricingRuleCreate) SetOperation(v videopricingrule.Operation) *VideoPricingRuleCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetResolution sets the "resolution" field.
func (_c *VideoPricingRuleCreate) SetResolution(v string) *VideoPricingRuleCreate {
	_c.mutation.SetResolution(v)
	return _c
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_c *VideoPricingRuleCreate) SetNillableResolution(v *string) *VideoPricingRuleCreate {
	if v != nil {
		_c.SetResolution(*v)
	}
	return _c
}

// SetAudioMode sets the "audio_mode" field.
func (_c *VideoPricingRuleCreate) SetAudioMode(v videopricingrule.AudioMode) *VideoPricingRuleCreate {
	_c.mutation.SetAudioMode(v)
	return _c
}

// SetNillableAudioMode sets the "audio_mode" field if the given value is not nil.
func (_c *VideoPricingRuleCreate) SetNillableAudioMode(v *videopricingrule.AudioMode) *VideoPricingRuleCreate {
	if v != nil {
		_c.SetAudioMode(*v)
	}
	return _c
}

// SetUnit sets the "unit" field.
func (_c *VideoPricingRuleCreate) SetUnit(v videopricingrule.Unit) *VideoPricingRuleCreate {
	_c.mutation.SetUnit(v)
	return _c
}

// SetUnitPrice sets the "unit_price" field.
func (_c *VideoPricingRuleCreate) SetUnitPrice(v float64) *VideoPricingRuleCreate {
	_c.mutation.SetUnitPrice(v)
	return _c
}

// SetUpstreamUnitCost sets the "upstream_unit_cost" field.
func (_c *VideoPricingRuleCreate) SetUpstreamUnitCost(v float64) *VideoPricingRuleCreate {
	_c.mutation.SetUpstreamUnitCost(v)
	return _c
}

// SetNillableUpstreamUnitCost sets the "upstream_unit_cost" field if the given value is not nil.
func (_c *VideoPricingRuleCreate) SetNillableUpstreamUnitCost(v *float64) *VideoPricingRuleCreate {
	if v != nil {
		_c.SetUpstreamUnitCost(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *VideoPricingRuleCreate) SetEnabled(v bool) *VideoPricingRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *VideoPricingRuleCreate) SetNillableEnabled(v *bool) *VideoPricingRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoPricingRuleCreate) SetCreatedAt(v time.Time) *VideoPricingRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoPricingRuleCreate) SetNillableCreatedAt(v *time.Time) *VideoPricingRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoPricingRuleCreate) SetUpdatedAt(v time.Time) *VideoPricingRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoPricingRuleCreate) SetNillableUpdatedAt(v *time.Time) *VideoPricingRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *VideoPricingRuleCreate) SetGroup(v *Group) *VideoPricingRuleCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the VideoPricingRuleMutation object of the builder.
func (_c *VideoPricingRuleCreate) Mutation() *VideoPricingRuleMutation {
	return _c.mutation
}

// Save creates the VideoPricingRule in the database.
func (_c *VideoPricingRuleCreate) Save(ctx context.Context) (*VideoPricingRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoPricingRuleCreate) SaveX(ctx context.Context) *VideoPricingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoPricingRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoPricingRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoPricingRuleCreate) defaults() {
	if _, ok := _c.mutation.Resolution(); !ok {
		v := videopricingrule.DefaultResolution
		_c.mutation.SetResolution(v)
	}
	if _, ok := _c.mutation.AudioMode(); !ok {
		v := videopricingrule.DefaultAudioMode
		_c.mutation.SetAudioMode(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := videopricingrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videopricingrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := videopricingrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoPricingRuleCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "VideoPricingRule.group_id"`)}
	}
	if _, ok := _c.mutation.ExternalModel(); !ok {
		return &ValidationError{Name: "external_model", err: errors.New(`ent: missing required field "VideoPricingRule.external_model"`)}
	}
	if v, ok := _c.mutation.ExternalModel(); ok {
		if err := videopricingrule.ExternalModelValidator(v); err != nil {
			return &ValidationError{Name: "external_model", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.external_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "VideoPricingRule.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := videopricingrule.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Resolution(); !ok {
		return &ValidationError{Name: "resolution", err: errors.New(`ent: missing required field "VideoPricingRule.resolution"`)}
	}
	if v, ok := _c.mutation.Resolution(); ok {
		if err := videopricingrule.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.resolution": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AudioMode(); !ok {
		return &ValidationError{Name: "audio_mode", err: errors.New(`ent: missing required field "VideoPricingRule.audio_mode"`)}
	}
	if v, ok := _c.mutation.AudioMode(); ok {
		if err := videopricingrule.AudioModeValidator(v); err != nil {
			return &ValidationError{Name: "audio_mode", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.audio_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Unit(); !ok {
		return &ValidationError{Name: "unit", err: errors.New(`ent: missing required field "VideoPricingRule.unit"`)}
	}
	if v, ok := _c.mutation.Unit(); ok {
		if err := videopricingrule.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		return &ValidationError{Name: "unit_price", err: errors.New(`ent: missing required field "VideoPricingRule.unit_price"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "VideoPricingRule.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoPricingRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoPricingRule.updated_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "VideoPricingRule.group"`)}
	}
	return nil
}

func (_c *VideoPricingRuleCreate) sqlSave(ctx context.Context) (*VideoPricingRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoPricingRuleCreate) createSpec() (*VideoPricingRule, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoPricingRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videopricingrule.Table, sqlgraph.NewFieldSpec(videopricingrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ExternalModel(); ok {
		_spec.SetField(videopricingrule.FieldExternalModel, field.TypeString, value)
		_node.ExternalModel = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(videopricingrule.FieldOperation, field.TypeEnum, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Resolution(); ok {
		_spec.SetField(videopricingrule.FieldResolution, field.TypeString, value)
		_node.Resolution = value
	}
	if value, ok := _c.mutation.AudioMode(); ok {
		_spec.SetField(videopricingrule.FieldAudioMode, field.TypeEnum, value)
		_node.AudioMode = value
	}
	if value, ok := _c.mutation.Unit(); ok {
		_spec.SetField(videopricingrule.FieldUnit, field.TypeEnum, value)
		_node.Unit = value
	}
	if value, ok := _c.mutation.UnitPrice(); ok {
		_spec.SetField(videopricingrule.FieldUnitPrice, field.TypeFloat64, value)
		_node.UnitPrice = value
	}
	if value, ok := _c.mutation.UpstreamUnitCost(); ok {
		_spec.SetField(videopricingrule.FieldUpstreamUnitCost, field.TypeFloat64, value)
		_node.UpstreamUnitCost = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(videopricingrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videopricingrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videopricingrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videopricingrule.GroupTable,
			Columns: []string{videopricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoPricingRule.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoPricingRuleUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoPricingRuleCreate) OnConflict(opts ...sql.ConflictOption) *VideoPricingRuleUpsertOne {
	_c.conflict = opts
	return &VideoPricingRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoPricingRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoPricingRuleCreate) OnConflictColumns(columns ...string) *VideoPricingRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoPricingRuleUpsertOne{
		create: _c,
	}
}

type (
	// VideoPricingRuleUpsertOne is the builder for "upsert"-ing
	//  one VideoPricingRule node.
	VideoPricingRuleUpsertOne struct {
		create *VideoPricingRuleCreate
	}

	// VideoPricingRuleUpsert is the "OnConflict" setter.
	VideoPricingRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *VideoPricingRuleUpsert) SetGroupID(v int64) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateGroupID() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldGroupID)
	return u
}

// SetExternalModel sets the "external_model" field.
func (u *VideoPricingRuleUpsert) SetExternalModel(v string) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldExternalModel, v)
	return u
}

// UpdateExternalModel sets the "external_model" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateExternalModel() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldExternalModel)
	return u
}

// SetOperation sets the "operation" field.
func (u *VideoPricingRuleUpsert) SetOperation(v videopricingrule.Operation) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldOperation, v)
	return u
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateOperation() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldOperation)
	return u
}

// SetResolution sets the "resolution" field.
func (u *VideoPricingRuleUpsert) SetResolution(v string) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldResolution, v)
	return u
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateResolution() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldResolution)
	return u
}

// SetAudioMode sets the "audio_mode" field.
func (u *VideoPricingRuleUpsert) SetAudioMode(v videopricingrule.AudioMode) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldAudioMode, v)
	return u
}

// UpdateAudioMode sets the "audio_mode" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateAudioMode() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldAudioMode)
	return u
}

// SetUnit sets the "unit" field.
func (u *VideoPricingRuleUpsert) SetUnit(v videopricingrule.Unit) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldUnit, v)
	return u
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateUnit() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldUnit)
	return u
}

// SetUnitPrice sets the "unit_price" field.
func (u *VideoPricingRuleUpsert) SetUnitPrice(v float64) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldUnitPrice, v)
	return u
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateUnitPrice() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldUnitPrice)
	return u
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *VideoPricingRuleUpsert) AddUnitPrice(v float64) *VideoPricingRuleUpsert {
	u.Add(videopricingrule.FieldUnitPrice, v)
	return u
}

// SetUpstreamUnitCost sets the "upstream_unit_cost" field.
func (u *VideoPricingRuleUpsert) SetUpstreamUnitCost(v float64) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldUpstreamUnitCost, v)
	return u
}

// UpdateUpstreamUnitCost sets the "upstream_unit_cost" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateUpstreamUnitCost() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldUpstreamUnitCost)
	return u
}

// AddUpstreamUnitCost adds v to the "upstream_unit_cost" field.
func (u *VideoPricingRuleUpsert) AddUpstreamUnitCost(v float64) *VideoPricingRuleUpsert {
	u.Add(videopricingrule.FieldUpstreamUnitCost, v)
	return u
}

// ClearUpstreamUnitCost clears the value of the "upstream_unit_cost" field.
func (u *VideoPricingRuleUpsert) ClearUpstreamUnitCost() *VideoPricingRuleUpsert {
	u.SetNull(videopricingrule.FieldUpstreamUnitCost)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *VideoPricingRuleUpsert) SetEnabled(v bool) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateEnabled() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldEnabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoPricingRuleUpsert) SetUpdatedAt(v time.Time) *VideoPricingRuleUpsert {
	u.Set(videopricingrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoPricingRuleUpsert) UpdateUpdatedAt() *VideoPricingRuleUpsert {
	u.SetExcluded(videopricingrule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoPricingRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoPricingRuleUpsertOne) UpdateNewValues() *VideoPricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videopricingrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoPricingRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoPricingRuleUpsertOne) Ignore() *VideoPricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoPricingRuleUpsertOne) DoNothing() *VideoPricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoPricingRuleCreate.OnConflict
// documentation for more info.
func (u *VideoPricingRuleUpsertOne) Update(set func(*VideoPricingRuleUpsert)) *VideoPricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoPricingRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *VideoPricingRuleUpsertOne) SetGroupID(v int64) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateGroupID() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateGroupID()
	})
}

// SetExternalModel sets the "external_model" field.
func (u *VideoPricingRuleUpsertOne) SetExternalModel(v string) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetExternalModel(v)
	})
}

// UpdateExternalModel sets the "external_model" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateExternalModel() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateExternalModel()
	})
}

// SetOperation sets the "operation" field.
func (u *VideoPricingRuleUpsertOne) SetOperation(v videopricingrule.Operation) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateOperation() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateOperation()
	})
}

// SetResolution sets the "resolution" field.
func (u *VideoPricingRuleUpsertOne) SetResolution(v string) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateResolution() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateResolution()
	})
}

// SetAudioMode sets the "audio_mode" field.
func (u *VideoPricingRuleUpsertOne) SetAudioMode(v videopricingrule.AudioMode) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetAudioMode(v)
	})
}

// UpdateAudioMode sets the "audio_mode" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateAudioMode() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateAudioMode()
	})
}

// SetUnit sets the "unit" field.
func (u *VideoPricingRuleUpsertOne) SetUnit(v videopricingrule.Unit) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateUnit() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateUnit()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *VideoPricingRuleUpsertOne) SetUnitPrice(v float64) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *VideoPricingRuleUpsertOne) AddUnitPrice(v float64) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateUnitPrice() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetUpstreamUnitCost sets the "upstream_unit_cost" field.
func (u *VideoPricingRuleUpsertOne) SetUpstreamUnitCost(v float64) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetUpstreamUnitCost(v)
	})
}

// AddUpstreamUnitCost adds v to the "upstream_unit_cost" field.
func (u *VideoPricingRuleUpsertOne) AddUpstreamUnitCost(v float64) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.AddUpstreamUnitCost(v)
	})
}

// UpdateUpstreamUnitCost sets the "upstream_unit_cost" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateUpstreamUnitCost() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateUpstreamUnitCost()
	})
}

// ClearUpstreamUnitCost clears the value of the "upstream_unit_cost" field.
func (u *VideoPricingRuleUpsertOne) ClearUpstreamUnitCost() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.ClearUpstreamUnitCost()
	})
}

// SetEnabled sets the "enabled" field.
func (u *VideoPricingRuleUpsertOne) SetEnabled(v bool) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateEnabled() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoPricingRuleUpsertOne) SetUpdatedAt(v time.Time) *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertOne) UpdateUpdatedAt() *VideoPricingRuleUpsertOne {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VideoPricingRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoPricingRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoPricingRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoPricingRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoPricingRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoPricingRuleCreateBulk is the builder for creating many VideoPricingRule entities in bulk.
type VideoPricingRuleCreateBulk struct {
	config
	err      error
	builders []*VideoPricingRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoPricingRule entities in the database.
func (_c *VideoPricingRuleCreateBulk) Save(ctx context.Context) ([]*VideoPricingRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoPricingRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoPricingRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoPricingRuleCreateBulk) SaveX(ctx context.Context) []*VideoPricingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoPricingRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoPricingRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoPricingRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoPricingRuleUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoPricingRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoPricingRuleUpsertBulk {
	_c.conflict = opts
	return &VideoPricingRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoPricingRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoPricingRuleCreateBulk) OnConflictColumns(columns ...string) *VideoPricingRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoPricingRuleUpsertBulk{
		create: _c,
	}
}

// VideoPricingRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoPricingRule nodes.
type VideoPricingRuleUpsertBulk struct {
	create *VideoPricingRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoPricingRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoPricingRuleUpsertBulk) UpdateNewValues() *VideoPricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videopricingrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoPricingRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoPricingRuleUpsertBulk) Ignore() *VideoPricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoPricingRuleUpsertBulk) DoNothing() *VideoPricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoPricingRuleCreateBulk.OnConflict
// documentation for more info.
func (u *VideoPricingRuleUpsertBulk) Update(set func(*VideoPricingRuleUpsert)) *VideoPricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoPricingRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *VideoPricingRuleUpsertBulk) SetGroupID(v int64) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateGroupID() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateGroupID()
	})
}

// SetExternalModel sets the "external_model" field.
func (u *VideoPricingRuleUpsertBulk) SetExternalModel(v string) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetExternalModel(v)
	})
}

// UpdateExternalModel sets the "external_model" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateExternalModel() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateExternalModel()
	})
}

// SetOperation sets the "operation" field.
func (u *VideoPricingRuleUpsertBulk) SetOperation(v videopricingrule.Operation) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateOperation() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateOperation()
	})
}

// SetResolution sets the "resolution" field.
func (u *VideoPricingRuleUpsertBulk) SetResolution(v string) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateResolution() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateResolution()
	})
}

// SetAudioMode sets the "audio_mode" field.
func (u *VideoPricingRuleUpsertBulk) SetAudioMode(v videopricingrule.AudioMode) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetAudioMode(v)
	})
}

// UpdateAudioMode sets the "audio_mode" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateAudioMode() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateAudioMode()
	})
}

// SetUnit sets the "unit" field.
func (u *VideoPricingRuleUpsertBulk) SetUnit(v videopricingrule.Unit) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateUnit() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateUnit()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *VideoPricingRuleUpsertBulk) SetUnitPrice(v float64) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *VideoPricingRuleUpsertBulk) AddUnitPrice(v float64) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateUnitPrice() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetUpstreamUnitCost sets the "upstream_unit_cost" field.
func (u *VideoPricingRuleUpsertBulk) SetUpstreamUnitCost(v float64) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetUpstreamUnitCost(v)
	})
}

// AddUpstreamUnitCost adds v to the "upstream_unit_cost" field.
func (u *VideoPricingRuleUpsertBulk) AddUpstreamUnitCost(v float64) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.AddUpstreamUnitCost(v)
	})
}

// UpdateUpstreamUnitCost sets the "upstream_unit_cost" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateUpstreamUnitCost() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateUpstreamUnitCost()
	})
}

// ClearUpstreamUnitCost clears the value of the "upstream_unit_cost" field.
func (u *VideoPricingRuleUpsertBulk) ClearUpstreamUnitCost() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.ClearUpstreamUnitCost()
	})
}

// SetEnabled sets the "enabled" field.
func (u *VideoPricingRuleUpsertBulk) SetEnabled(v bool) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateEnabled() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoPricingRuleUpsertBulk) SetUpdatedAt(v time.Time) *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoPricingRuleUpsertBulk) UpdateUpdatedAt() *VideoPricingRuleUpsertBulk {
	return u.Update(func(s *VideoPricingRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VideoPricingRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoPricingRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoPricingRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoPricingRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
