// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/videopricingrule"
)

// VideoPricingRuleUpdate is the builder for updating VideoPricingRule entities.
type VideoPricingRuleUpdate struct {
	config
	hooks    []Hook
	mutation *VideoPricingRuleMutation
}

// Where appends a list predicates to the VideoPricingRuleUpdate builder.
func (_u *VideoPricingRuleUpdate) Where(ps ...predicate.VideoPricingRule) *VideoPricingRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoPricingRuleUpdate) SetGroupID(v int64) *VideoPricingRuleUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoPricingRuleUpdate) SetNillableGroupID(v *int64) *VideoPricingRuleUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetExternalModel sets the "external_model" field.
func (_u *VideoPricingRuleUpdate) SetExternalModel(v string) *VideoPricingRuleUpdate {
	_u.mutation.SetExternalModel(v)
	return _u
}

// SetNillableExternalModel sets the "external_model" field if the given value is not nil.
func (_u *VideoPricingRuleUpdate) SetNillableExternalModel(v *string) *VideoPricingRuleUpdate {
	if v != nil {
		_u.SetExternalModel(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *VideoPricingRuleUpdate) SetOperation(v videopricingrule.Operation) *VideoPricingRuleUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *VideoPricingRuleUpdate) SetNillableOperation(v *videopricingrule.Operation) *VideoPricingRuleUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *VideoPricingRuleUpdate) SetResolution(v string) *VideoPricingRuleUpdate {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *VideoPricingRuleUpdate) SetNillableResolution(v *string) *VideoPricingRuleUpdate {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// SetAudioMode sets the "audio_mode" field.
func (_u *VideoPricingRuleUpdate) SetAudioMode(v videopricingrule.AudioMode) *VideoPricingRuleUpdate {
	_u.mutation.SetAudioMode(v)
	return _u
}

// SetNillableAudioMode sets the "audio_mode" field if the given value is not nil.
func (_u *VideoPricingRuleUpdate) SetNillableAudioMode(v *videopricingrule.AudioMode) *VideoPricingRuleUpdate {
	if v != nil {
		_u.SetAudioMode(*v)
	}
	return _u
}

// SetUnit sets the "unit" field.
func (_u *VideoPricingRuleUpdate) SetUnit(v videopricingrule.Unit) *VideoPricingRuleUpdate {
	_u.mutation.SetUnit(v)
	return _u
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_u *VideoPricingRuleUpdate) SetNillableUnit(v *videopricingrule.Unit) *VideoPricingRuleUpdate {
	if v != nil {
		_u.SetUnit(*v)
	}
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *VideoPricingRuleUpdate) SetUnitPrice(v float64) *VideoPricingRuleUpdate {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *VideoPricingRuleUpdate) SetNillableUnitPrice(v *float64) *VideoPricingRuleUpdate {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *VideoPricingRuleUpdate) AddUnitPrice(v float64) *VideoPricingRuleUpdate {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetUpstreamUnitCost sets the "upstream_unit_cost" field.
func (_u *VideoPricingRuleUpdate) SetUpstreamUnitCost(v float64) *VideoPricingRuleUpdate {
	_u.mutation.ResetUpstreamUnitCost()
	_u.mutation.SetUpstreamUnitCost(v)
	return _u
}

// SetNillableUpstreamUnitCost sets the "upstream_unit_cost" field if the given value is not nil.
func (_u *VideoPricingRuleUpdate) SetNillableUpstreamUnitCost(v *float64) *VideoPricingRuleUpdate {
	if v != nil {
		_u.SetUpstreamUnitCost(*v)
	}
	return _u
}

// AddUpstreamUnitCost adds value to the "upstream_unit_cost" field.
func (_u *VideoPricingRuleUpdate) AddUpstreamUnitCost(v float64) *VideoPricingRuleUpdate {
	_u.mutation.AddUpstreamUnitCost(v)
	return _u
}

// ClearUpstreamUnitCost clears the value of the "upstream_unit_cost" field.
func (_u *VideoPricingRuleUpdate) ClearUpstreamUnitCost() *VideoPricingRuleUpdate {
	_u.mutation.ClearUpstreamUnitCost()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *VideoPricingRuleUpdate) SetEnabled(v bool) *VideoPricingRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *VideoPricingRuleUpdate) SetNillableEnabled(v *bool) *VideoPricingRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoPricingRuleUpdate) SetUpdatedAt(v time.Time) *VideoPricingRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *VideoPricingRuleUpdate) SetGroup(v *Group) *VideoPricingRuleUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the VideoPricingRuleMutation object of the builder.
func (_u *VideoPricingRuleUpdate) Mutation() *VideoPricingRuleMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *VideoPricingRuleUpdate) ClearGroup() *VideoPricingRuleUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoPricingRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoPricingRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoPricingRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoPricingRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoPricingRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videopricingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoPricingRuleUpdate) check() error {
	if v, ok := _u.mutation.ExternalModel(); ok {
		if err := videopricingrule.ExternalModelValidator(v); err != nil {
			return &ValidationError{Name: "external_model", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.external_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := videopricingrule.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := videopricingrule.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AudioMode(); ok {
		if err := videopricingrule.AudioModeValidator(v); err != nil {
			return &ValidationError{Name: "audio_mode", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.audio_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Unit(); ok {
		if err := videopricingrule.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.unit": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoPricingRule.group"`)
	}
	return nil
}

func (_u *VideoPricingRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videopricingrule.Table, videopricingrule.Columns, sqlgraph.NewFieldSpec(videopricingrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalModel(); ok {
		_spec.SetField(videopricingrule.FieldExternalModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(videopricingrule.FieldOperation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(videopricingrule.FieldResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.AudioMode(); ok {
		_spec.SetField(videopricingrule.FieldAudioMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(videopricingrule.FieldUnit, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(videopricingrule.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(videopricingrule.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpstreamUnitCost(); ok {
		_spec.SetField(videopricingrule.FieldUpstreamUnitCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamUnitCost(); ok {
		_spec.AddField(videopricingrule.FieldUpstreamUnitCost, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamUnitCostCleared() {
		_spec.ClearField(videopricingrule.FieldUpstreamUnitCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(videopricingrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videopricingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videopricingrule.GroupTable,
			Columns: []string{videopricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videopricingrule.GroupTable,
			Columns: []string{videopricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videopricingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoPricingRuleUpdateOne is the builder for updating a single VideoPricingRule entity.
type VideoPricingRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoPricingRuleMutation
}

// SetGroupID sets the "group_id" field.
func (_u *VideoPricingRuleUpdateOne) SetGroupID(v int64) *VideoPricingRuleUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoPricingRuleUpdateOne) SetNillableGroupID(v *int64) *VideoPricingRuleUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetExternalModel sets the "external_model" field.
func (_u *VideoPricingRuleUpdateOne) SetExternalModel(v string) *VideoPricingRuleUpdateOne {
	_u.mutation.SetExternalModel(v)
	return _u
}

// SetNillableExternalModel sets the "external_model" field if the given value is not nil.
func (_u *VideoPricingRuleUpdateOne) SetNillableExternalModel(v *string) *VideoPricingRuleUpdateOne {
	if v != nil {
		_u.SetExternalModel(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *VideoPricingRuleUpdateOne) SetOperation(v videopricingrule.Operation) *VideoPricingRuleUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *VideoPricingRuleUpdateOne) SetNillableOperation(v *videopricingrule.Operation) *VideoPricingRuleUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *VideoPricingRuleUpdateOne) SetResolution(v string) *VideoPricingRuleUpdateOne {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *VideoPricingRuleUpdateOne) SetNillableResolution(v *string) *VideoPricingRuleUpdateOne {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// SetAudioMode sets the "audio_mode" field.
func (_u *VideoPricingRuleUpdateOne) SetAudioMode(v videopricingrule.AudioMode) *VideoPricingRuleUpdateOne {
	_u.mutation.SetAudioMode(v)
	return _u
}

// SetNillableAudioMode sets the "audio_mode" field if the given value is not nil.
func (_u *VideoPricingRuleUpdateOne) SetNillableAudioMode(v *videopricingrule.AudioMode) *VideoPricingRuleUpdateOne {
	if v != nil {
		_u.SetAudioMode(*v)
	}
	return _u
}

// SetUnit sets the "unit" field.
func (_u *VideoPricingRuleUpdateOne) SetUnit(v videopricingrule.Unit) *VideoPricingRuleUpdateOne {
	_u.mutation.SetUnit(v)
	return _u
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_u *VideoPricingRuleUpdateOne) SetNillableUnit(v *videopricingrule.Unit) *VideoPricingRuleUpdateOne {
	if v != nil {
		_u.SetUnit(*v)
	}
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *VideoPricingRuleUpdateOne) SetUnitPrice(v float64) *VideoPricingRuleUpdateOne {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *VideoPricingRuleUpdateOne) SetNillableUnitPrice(v *float64) *VideoPricingRuleUpdateOne {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *VideoPricingRuleUpdateOne) AddUnitPrice(v float64) *VideoPricingRuleUpdateOne {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetUpstreamUnitCost sets the "upstream_unit_cost" field.
func (_u *VideoPricingRuleUpdateOne) SetUpstreamUnitCost(v float64) *VideoPricingRuleUpdateOne {
	_u.mutation.ResetUpstreamUnitCost()
	_u.mutation.SetUpstreamUnitCost(v)
	return _u
}

// SetNillableUpstreamUnitCost sets the "upstream_unit_cost" field if the given value is not nil.
func (_u *VideoPricingRuleUpdateOne) SetNillableUpstreamUnitCost(v *float64) *VideoPricingRuleUpdateOne {
	if v != nil {
		_u.SetUpstreamUnitCost(*v)
	}
	return _u
}

// AddUpstreamUnitCost adds value to the "upstream_unit_cost" field.
func (_u *VideoPricingRuleUpdateOne) AddUpstreamUnitCost(v float64) *VideoPricingRuleUpdateOne {
	_u.mutation.AddUpstreamUnitCost(v)
	return _u
}

// ClearUpstreamUnitCost clears the value of the "upstream_unit_cost" field.
func (_u *VideoPricingRuleUpdateOne) ClearUpstreamUnitCost() *VideoPricingRuleUpdateOne {
	_u.mutation.ClearUpstreamUnitCost()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *VideoPricingRuleUpdateOne) SetEnabled(v bool) *VideoPricingRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *VideoPricingRuleUpdateOne) SetNillableEnabled(v *bool) *VideoPricingRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoPricingRuleUpdateOne) SetUpdatedAt(v time.Time) *VideoPricingRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *VideoPricingRuleUpdateOne) SetGroup(v *Group) *VideoPricingRuleUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the VideoPricingRuleMutation object of the builder.
func (_u *VideoPricingRuleUpdateOne) Mutation() *VideoPricingRuleMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *VideoPricingRuleUpdateOne) ClearGroup() *VideoPricingRuleUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the VideoPricingRuleUpdate builder.
func (_u *VideoPricingRuleUpdateOne) Where(ps ...predicate.VideoPricingRule) *VideoPricingRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoPricingRuleUpdateOne) Select(field string, fields ...string) *VideoPricingRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoPricingRule entity.
func (_u *VideoPricingRuleUpdateOne) Save(ctx context.Context) (*VideoPricingRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoPricingRuleUpdateOne) SaveX(ctx context.Context) *VideoPricingRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoPricingRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoPricingRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoPricingRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videopricingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoPricingRuleUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalModel(); ok {
		if err := videopricingrule.ExternalModelValidator(v); err != nil {
			return &ValidationError{Name: "external_model", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.external_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := videopricingrule.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := videopricingrule.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AudioMode(); ok {
		if err := videopricingrule.AudioModeValidator(v); err != nil {
			return &ValidationError{Name: "audio_mode", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.audio_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Unit(); ok {
		if err := videopricingrule.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "VideoPricingRule.unit": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoPricingRule.group"`)
	}
	return nil
}

func (_u *VideoPricingRuleUpdateOne) sqlSave(ctx context.Context) (_node *VideoPricingRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videopricingrule.Table, videopricingrule.Columns, sqlgraph.NewFieldSpec(videopricingrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoPricingRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videopricingrule.FieldID)
		for _, f := range fields {
			if !videopricingrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videopricingrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalModel(); ok {
		_spec.SetField(videopricingrule.FieldExternalModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(videopricingrule.FieldOperation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(videopricingrule.FieldResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.AudioMode(); ok {
		_spec.SetField(videopricingrule.FieldAudioMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(videopricingrule.FieldUnit, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(videopricingrule.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(videopricingrule.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpstreamUnitCost(); ok {
		_spec.SetField(videopricingrule.FieldUpstreamUnitCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamUnitCost(); ok {
		_spec.AddField(videopricingrule.FieldUpstreamUnitCost, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamUnitCostCleared() {
		_spec.ClearField(videopricingrule.FieldUpstreamUnitCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(videopricingrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videopricingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videopricingrule.GroupTable,
			Columns: []string{videopricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videopricingrule.GroupTable,
			Columns: []string{videopricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VideoPricingRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videopricingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
