// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/videopricingrule"
)

// VideoPricingRule is the model entity for the VideoPricingRule schema.
type VideoPricingRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// ExternalModel holds the value of the "external_model" field.
	ExternalModel string `json:"external_model,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation videopricingrule.Operation `json:"operation,omitempty"`
	// Resolution holds the value of the "resolution" field.
	Resolution string `json:"resolution,omitempty"`
	// AudioMode holds the value of the "audio_mode" field.
	AudioMode videopricingrule.AudioMode `json:"audio_mode,omitempty"`
	// Unit holds the value of the "unit" field.
	Unit videopricingrule.Unit `json:"unit,omitempty"`
	// UnitPrice holds the value of the "unit_price" field.
	UnitPrice float64 `json:"unit_price,omitempty"`
	// UpstreamUnitCost holds the value of the "upstream_unit_cost" field.
	UpstreamUnitCost *float64 `json:"upstream_unit_cost,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VideoPricingRuleQuery when eager-loading is set.
	Edges        VideoPricingRuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VideoPricingRuleEdges holds the relations/edges for other nodes in the graph.
type VideoPricingRuleEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VideoPricingRuleEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoPricingRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videopricingrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case videopricingrule.FieldUnitPrice, videopricingrule.FieldUpstreamUnitCost:
			values[i] = new(sql.NullFloat64)
		case videopricingrule.FieldID, videopricingrule.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case videopricingrule.FieldExternalModel, videopricingrule.FieldOperation, videopricingrule.FieldResolution, videopricingrule.FieldAudioMode, videopricingrule.FieldUnit:
			values[i] = new(sql.NullString)
		case videopricingrule.FieldCreatedAt, videopricingrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoPricingRule fields.
func (_m *VideoPricingRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videopricingrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case videopricingrule.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case videopricingrule.FieldExternalModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_model", values[i])
			} else if value.Valid {
				_m.ExternalModel = value.String
			}
		case videopricingrule.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = videopricingrule.Operation(value.String)
			}
		case videopricingrule.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				_m.Resolution = value.String
			}
		case videopricingrule.FieldAudioMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audio_mode", values[i])
			} else if value.Valid {
				_m.AudioMode = videopricingrule.AudioMode(value.String)
			}
		case videopricingrule.FieldUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unit", values[i])
			} else if value.Valid {
				_m.Unit = videopricingrule.Unit(value.String)
			}
		case videopricingrule.FieldUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price", values[i])
			} else if value.Valid {
				_m.UnitPrice = value.Float64
			}
		case videopricingrule.FieldUpstreamUnitCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_unit_cost", values[i])
			} else if value.Valid {
				_m.UpstreamUnitCost = new(float64)
				*_m.UpstreamUnitCost = value.Float64
			}
		case videopricingrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case videopricingrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videopricingrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoPricingRule.
// This includes values selected through modifiers, order, etc.
func (_m *VideoPricingRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the VideoPricingRule entity.
func (_m *VideoPricingRule) QueryGroup() *GroupQuery {
	return NewVideoPricingRuleClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this VideoPricingRule.
// Note that you need to call VideoPricingRule.Unwrap() before calling this method if this VideoPricingRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoPricingRule) Update() *VideoPricingRuleUpdateOne {
	return NewVideoPricingRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoPricingRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoPricingRule) Unwrap() *VideoPricingRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoPricingRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoPricingRule) String() string {
	var builder strings.Builder
	builder.WriteString("VideoPricingRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("external_model=")
	builder.WriteString(_m.ExternalModel)
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Operation))
	builder.WriteString(", ")
	builder.WriteString("resolution=")
	builder.WriteString(_m.Resolution)
	builder.WriteString(", ")
	builder.WriteString("audio_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.AudioMode))
	builder.WriteString(", ")
	builder.WriteString("unit=")
	builder.WriteString(fmt.Sprintf("%v", _m.Unit))
	builder.WriteString(", ")
	builder.WriteString("unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitPrice))
	builder.WriteString(", ")
	if v := _m.UpstreamUnitCost; v != nil {
		builder.WriteString("upstream_unit_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VideoPricingRules is a parsable slice of VideoPricingRule.
type VideoPricingRules []*VideoPricingRule
