// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTask is the model entity for the VideoTask schema.
type VideoTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform videotask.Platform `json:"platform,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider videotask.Provider `json:"provider,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation videotask.Operation `json:"operation,omitempty"`
	// ExternalModel holds the value of the "external_model" field.
	ExternalModel string `json:"external_model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// IdempotencyKeyHash stores the caller key digest. Migration 200 enforces a partial unique index with user_id and api_key_id when this value is non-empty.
	IdempotencyKeyHash string `json:"idempotency_key_hash,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// ProviderSubmissionToken holds the value of the "provider_submission_token" field.
	ProviderSubmissionToken *string `json:"provider_submission_token,omitempty"`
	// RequestPayload holds the value of the "request_payload" field.
	RequestPayload json.RawMessage `json:"request_payload,omitempty"`
	// Status holds the value of the "status" field.
	Status videotask.Status `json:"status,omitempty"`
	// UpstreamTaskID holds the value of the "upstream_task_id" field.
	UpstreamTaskID *string `json:"upstream_task_id,omitempty"`
	// UpstreamStatus holds the value of the "upstream_status" field.
	UpstreamStatus *string `json:"upstream_status,omitempty"`
	// ResultURL holds the value of the "result_url" field.
	ResultURL *string `json:"result_url,omitempty"`
	// ResultURLExpiresAt holds the value of the "result_url_expires_at" field.
	ResultURLExpiresAt *time.Time `json:"result_url_expires_at,omitempty"`
	// ResultContentType holds the value of the "result_content_type" field.
	ResultContentType *string `json:"result_content_type,omitempty"`
	// ResultDurationSeconds holds the value of the "result_duration_seconds" field.
	ResultDurationSeconds *float64 `json:"result_duration_seconds,omitempty"`
	// ResultWidth holds the value of the "result_width" field.
	ResultWidth *int `json:"result_width,omitempty"`
	// ResultHeight holds the value of the "result_height" field.
	ResultHeight *int `json:"result_height,omitempty"`
	// PricingUnit holds the value of the "pricing_unit" field.
	PricingUnit string `json:"pricing_unit,omitempty"`
	// UnitPrice holds the value of the "unit_price" field.
	UnitPrice float64 `json:"unit_price,omitempty"`
	// UpstreamUnitCost holds the value of the "upstream_unit_cost" field.
	UpstreamUnitCost *float64 `json:"upstream_unit_cost,omitempty"`
	// EstimatedUnits holds the value of the "estimated_units" field.
	EstimatedUnits float64 `json:"estimated_units,omitempty"`
	// EstimatedAmount holds the value of the "estimated_amount" field.
	EstimatedAmount float64 `json:"estimated_amount,omitempty"`
	// FrozenAmount holds the value of the "frozen_amount" field.
	FrozenAmount float64 `json:"frozen_amount,omitempty"`
	// SettledAmount holds the value of the "settled_amount" field.
	SettledAmount *float64 `json:"settled_amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// BillingMode holds the value of the "billing_mode" field.
	BillingMode string `json:"billing_mode,omitempty"`
	// BillingStatus holds the value of the "billing_status" field.
	BillingStatus string `json:"billing_status,omitempty"`
	// BillingReference holds the value of the "billing_reference" field.
	BillingReference *string `json:"billing_reference,omitempty"`
	// SubmissionAttempts holds the value of the "submission_attempts" field.
	SubmissionAttempts int `json:"submission_attempts,omitempty"`
	// PollAttempts holds the value of the "poll_attempts" field.
	PollAttempts int `json:"poll_attempts,omitempty"`
	// SettlementAttempts holds the value of the "settlement_attempts" field.
	SettlementAttempts int `json:"settlement_attempts,omitempty"`
	// NextPollAt holds the value of the "next_poll_at" field.
	NextPollAt *time.Time `json:"next_poll_at,omitempty"`
	// LeaseOwner holds the value of the "lease_owner" field.
	LeaseOwner *string `json:"lease_owner,omitempty"`
	// LeaseExpiresAt holds the value of the "lease_expires_at" field.
	LeaseExpiresAt *time.Time `json:"lease_expires_at,omitempty"`
	// LastErrorCode holds the value of the "last_error_code" field.
	LastErrorCode *string `json:"last_error_code,omitempty"`
	// LastErrorMessage holds the value of the "last_error_message" field.
	LastErrorMessage *string `json:"last_error_message,omitempty"`
	// LastErrorRetryable holds the value of the "last_error_retryable" field.
	LastErrorRetryable bool `json:"last_error_retryable,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt    *time.Time `json:"settled_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videotask.FieldRequestPayload:
			values[i] = new([]byte)
		case videotask.FieldLastErrorRetryable:
			values[i] = new(sql.NullBool)
		case videotask.FieldResultDurationSeconds, videotask.FieldUnitPrice, videotask.FieldUpstreamUnitCost, videotask.FieldEstimatedUnits, videotask.FieldEstimatedAmount, videotask.FieldFrozenAmount, videotask.FieldSettledAmount:
			values[i] = new(sql.NullFloat64)
		case videotask.FieldID, videotask.FieldUserID, videotask.FieldAPIKeyID, videotask.FieldSubscriptionID, videotask.FieldGroupID, videotask.FieldAccountID, videotask.FieldResultWidth, videotask.FieldResultHeight, videotask.FieldSubmissionAttempts, videotask.FieldPollAttempts, videotask.FieldSettlementAttempts, videotask.FieldVersion:
			values[i] = new(sql.NullInt64)
		case videotask.FieldRequestID, videotask.FieldPlatform, videotask.FieldProvider, videotask.FieldOperation, videotask.FieldExternalModel, videotask.FieldUpstreamModel, videotask.FieldIdempotencyKeyHash, videotask.FieldRequestHash, videotask.FieldProviderSubmissionToken, videotask.FieldStatus, videotask.FieldUpstreamTaskID, videotask.FieldUpstreamStatus, videotask.FieldResultURL, videotask.FieldResultContentType, videotask.FieldPricingUnit, videotask.FieldCurrency, videotask.FieldBillingMode, videotask.FieldBillingStatus, videotask.FieldBillingReference, videotask.FieldLeaseOwner, videotask.FieldLastErrorCode, videotask.FieldLastErrorMessage:
			values[i] = new(sql.NullString)
		case videotask.FieldResultURLExpiresAt, videotask.FieldNextPollAt, videotask.FieldLeaseExpiresAt, videotask.FieldCreatedAt, videotask.FieldUpdatedAt, videotask.FieldSubmittedAt, videotask.FieldStartedAt, videotask.FieldFinishedAt, videotask.FieldSettledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoTask fields.
func (_m *VideoTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videotask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case videotask.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case videotask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case videotask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case videotask.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int64)
				*_m.SubscriptionID = value.Int64
			}
		case videotask.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case videotask.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case videotask.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = videotask.Platform(value.String)
			}
		case videotask.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = videotask.Provider(value.String)
			}
		case videotask.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = videotask.Operation(value.String)
			}
		case videotask.FieldExternalModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_model", values[i])
			} else if value.Valid {
				_m.ExternalModel = value.String
			}
		case videotask.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case videotask.FieldIdempotencyKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key_hash", values[i])
			} else if value.Valid {
				_m.IdempotencyKeyHash = value.String
			}
		case videotask.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		case videotask.FieldProviderSubmissionToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_submission_token", values[i])
			} else if value.Valid {
				_m.ProviderSubmissionToken = new(string)
				*_m.ProviderSubmissionToken = value.String
			}
		case videotask.FieldRequestPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestPayload); err != nil {
					return fmt.Errorf("unmarshal field request_payload: %w", err)
				}
			}
		case videotask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = videotask.Status(value.String)
			}
		case videotask.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = new(string)
				*_m.UpstreamTaskID = value.String
			}
		case videotask.FieldUpstreamStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status", values[i])
			} else if value.Valid {
				_m.UpstreamStatus = new(string)
				*_m.UpstreamStatus = value.String
			}
		case videotask.FieldResultURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_url", values[i])
			} else if value.Valid {
				_m.ResultURL = new(string)
				*_m.ResultURL = value.String
			}
		case videotask.FieldResultURLExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field result_url_expires_at", values[i])
			} else if value.Valid {
				_m.ResultURLExpiresAt = new(time.Time)
				*_m.ResultURLExpiresAt = value.Time
			}
		case videotask.FieldResultContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_content_type", values[i])
			} else if value.Valid {
				_m.ResultContentType = new(string)
				*_m.ResultContentType = value.String
			}
		case videotask.FieldResultDurationSeconds:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field result_duration_seconds", values[i])
			} else if value.Valid {
				_m.ResultDurationSeconds = new(float64)
				*_m.ResultDurationSeconds = value.Float64
			}
		case videotask.FieldResultWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field result_width", values[i])
			} else if value.Valid {
				_m.ResultWidth = new(int)
				*_m.ResultWidth = int(value.Int64)
			}
		case videotask.FieldResultHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field result_height", values[i])
			} else if value.Valid {
				_m.ResultHeight = new(int)
				*_m.ResultHeight = int(value.Int64)
			}
		case videotask.FieldPricingUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_unit", values[i])
			} else if value.Valid {
				_m.PricingUnit = value.String
			}
		case videotask.FieldUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price", values[i])
			} else if value.Valid {
				_m.UnitPrice = value.Float64
			}
		case videotask.FieldUpstreamUnitCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_unit_cost", values[i])
			} else if value.Valid {
				_m.UpstreamUnitCost = new(float64)
				*_m.UpstreamUnitCost = value.Float64
			}
		case videotask.FieldEstimatedUnits:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_units", values[i])
			} else if value.Valid {
				_m.EstimatedUnits = value.Float64
			}
		case videotask.FieldEstimatedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_amount", values[i])
			} else if value.Valid {
				_m.EstimatedAmount = value.Float64
			}
		case videotask.FieldFrozenAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_amount", values[i])
			} else if value.Valid {
				_m.FrozenAmount = value.Float64
			}
		case videotask.FieldSettledAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field settled_amount", values[i])
			} else if value.Valid {
				_m.SettledAmount = new(float64)
				*_m.SettledAmount = value.Float64
			}
		case videotask.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case videotask.FieldBillingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_mode", values[i])
			} else if value.Valid {
				_m.BillingMode = value.String
			}
		case videotask.FieldBillingStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_status", values[i])
			} else if value.Valid {
				_m.BillingStatus = value.String
			}
		case videotask.FieldBillingReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_reference", values[i])
			} else if value.Valid {
				_m.BillingReference = new(string)
				*_m.BillingReference = value.String
			}
		case videotask.FieldSubmissionAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field submission_attempts", values[i])
			} else if value.Valid {
				_m.SubmissionAttempts = int(value.Int64)
			}
		case videotask.FieldPollAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field poll_attempts", values[i])
			} else if value.Valid {
				_m.PollAttempts = int(value.Int64)
			}
		case videotask.FieldSettlementAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_attempts", values[i])
			} else if value.Valid {
				_m.SettlementAttempts = int(value.Int64)
			}
		case videotask.FieldNextPollAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_poll_at", values[i])
			} else if value.Valid {
				_m.NextPollAt = new(time.Time)
				*_m.NextPollAt = value.Time
			}
		case videotask.FieldLeaseOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_owner", values[i])
			} else if value.Valid {
				_m.LeaseOwner = new(string)
				*_m.LeaseOwner = value.String
			}
		case videotask.FieldLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_expires_at", values[i])
			} else if value.Valid {
				_m.LeaseExpiresAt = new(time.Time)
				*_m.LeaseExpiresAt = value.Time
			}
		case videotask.FieldLastErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_code", values[i])
			} else if value.Valid {
				_m.LastErrorCode = new(string)
				*_m.LastErrorCode = value.String
			}
		case videotask.FieldLastErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_message", values[i])
			} else if value.Valid {
				_m.LastErrorMessage = new(string)
				*_m.LastErrorMessage = value.String
			}
		case videotask.FieldLastErrorRetryable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_retryable", values[i])
			} else if value.Valid {
				_m.LastErrorRetryable = value.Bool
			}
		case videotask.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case videotask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videotask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case videotask.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case videotask.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case videotask.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case videotask.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoTask.
// This includes values selected through modifiers, order, etc.
func (_m *VideoTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VideoTask.
// Note that you need to call VideoTask.Unwrap() before calling this method if this VideoTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoTask) Update() *VideoTaskUpdateOne {
	return NewVideoTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoTask) Unwrap() *VideoTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoTask) String() string {
	var builder strings.Builder
	builder.WriteString("VideoTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.Provider))
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Operation))
	builder.WriteString(", ")
	builder.WriteString("external_model=")
	builder.WriteString(_m.ExternalModel)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key_hash=")
	builder.WriteString(_m.IdempotencyKeyHash)
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteString(", ")
	if v := _m.ProviderSubmissionToken; v != nil {
		builder.WriteString("provider_submission_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("request_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestPayload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.UpstreamTaskID; v != nil {
		builder.WriteString("upstream_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamStatus; v != nil {
		builder.WriteString("upstream_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResultURL; v != nil {
		builder.WriteString("result_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResultURLExpiresAt; v != nil {
		builder.WriteString("result_url_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResultContentType; v != nil {
		builder.WriteString("result_content_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResultDurationSeconds; v != nil {
		builder.WriteString("result_duration_seconds=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResultWidth; v != nil {
		builder.WriteString("result_width=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResultHeight; v != nil {
		builder.WriteString("result_height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("pricing_unit=")
	builder.WriteString(_m.PricingUnit)
	builder.WriteString(", ")
	builder.WriteString("unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitPrice))
	builder.WriteString(", ")
	if v := _m.UpstreamUnitCost; v != nil {
		builder.WriteString("upstream_unit_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("estimated_units=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedUnits))
	builder.WriteString(", ")
	builder.WriteString("estimated_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedAmount))
	builder.WriteString(", ")
	builder.WriteString("frozen_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.FrozenAmount))
	builder.WriteString(", ")
	if v := _m.SettledAmount; v != nil {
		builder.WriteString("settled_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("billing_mode=")
	builder.WriteString(_m.BillingMode)
	builder.WriteString(", ")
	builder.WriteString("billing_status=")
	builder.WriteString(_m.BillingStatus)
	builder.WriteString(", ")
	if v := _m.BillingReference; v != nil {
		builder.WriteString("billing_reference=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("submission_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubmissionAttempts))
	builder.WriteString(", ")
	builder.WriteString("poll_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollAttempts))
	builder.WriteString(", ")
	builder.WriteString("settlement_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettlementAttempts))
	builder.WriteString(", ")
	if v := _m.NextPollAt; v != nil {
		builder.WriteString("next_poll_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LeaseOwner; v != nil {
		builder.WriteString("lease_owner=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseExpiresAt; v != nil {
		builder.WriteString("lease_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastErrorCode; v != nil {
		builder.WriteString("last_error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastErrorMessage; v != nil {
		builder.WriteString("last_error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("last_error_retryable=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastErrorRetryable))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// VideoTasks is a parsable slice of VideoTask.
type VideoTasks []*VideoTask
