// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/videotaskevent"
)

// VideoTaskEventUpdate is the builder for updating VideoTaskEvent entities.
type VideoTaskEventUpdate struct {
	config
	hooks    []Hook
	mutation *VideoTaskEventMutation
}

// Where appends a list predicates to the VideoTaskEventUpdate builder.
func (_u *VideoTaskEventUpdate) Where(ps ...predicate.VideoTaskEvent) *VideoTaskEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *VideoTaskEventUpdate) SetRequestID(v string) *VideoTaskEventUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *VideoTaskEventUpdate) SetNillableRequestID(v *string) *VideoTaskEventUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *VideoTaskEventUpdate) SetEventType(v string) *VideoTaskEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *VideoTaskEventUpdate) SetNillableEventType(v *string) *VideoTaskEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *VideoTaskEventUpdate) SetPayload(v json.RawMessage) *VideoTaskEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *VideoTaskEventUpdate) AppendPayload(v json.RawMessage) *VideoTaskEventUpdate {
	_u.mutation.AppendPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *VideoTaskEventUpdate) ClearPayload() *VideoTaskEventUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// Mutation returns the VideoTaskEventMutation object of the builder.
func (_u *VideoTaskEventUpdate) Mutation() *VideoTaskEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoTaskEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoTaskEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskEventUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := videotaskevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "VideoTaskEvent.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := videotaskevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "VideoTaskEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoTaskEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotaskevent.Table, videotaskevent.Columns, sqlgraph.NewFieldSpec(videotaskevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(videotaskevent.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(videotaskevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(videotaskevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, videotaskevent.FieldPayload, value)
		})
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(videotaskevent.FieldPayload, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotaskevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoTaskEventUpdateOne is the builder for updating a single VideoTaskEvent entity.
type VideoTaskEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoTaskEventMutation
}

// SetRequestID sets the "request_id" field.
func (_u *VideoTaskEventUpdateOne) SetRequestID(v string) *VideoTaskEventUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *VideoTaskEventUpdateOne) SetNillableRequestID(v *string) *VideoTaskEventUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *VideoTaskEventUpdateOne) SetEventType(v string) *VideoTaskEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *VideoTaskEventUpdateOne) SetNillableEventType(v *string) *VideoTaskEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *VideoTaskEventUpdateOne) SetPayload(v json.RawMessage) *VideoTaskEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *VideoTaskEventUpdateOne) AppendPayload(v json.RawMessage) *VideoTaskEventUpdateOne {
	_u.mutation.AppendPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *VideoTaskEventUpdateOne) ClearPayload() *VideoTaskEventUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// Mutation returns the VideoTaskEventMutation object of the builder.
func (_u *VideoTaskEventUpdateOne) Mutation() *VideoTaskEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the VideoTaskEventUpdate builder.
func (_u *VideoTaskEventUpdateOne) Where(ps ...predicate.VideoTaskEvent) *VideoTaskEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoTaskEventUpdateOne) Select(field string, fields ...string) *VideoTaskEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoTaskEvent entity.
func (_u *VideoTaskEventUpdateOne) Save(ctx context.Context) (*VideoTaskEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskEventUpdateOne) SaveX(ctx context.Context) *VideoTaskEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoTaskEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskEventUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := videotaskevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "VideoTaskEvent.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := videotaskevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "VideoTaskEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoTaskEventUpdateOne) sqlSave(ctx context.Context) (_node *VideoTaskEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotaskevent.Table, videotaskevent.Columns, sqlgraph.NewFieldSpec(videotaskevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoTaskEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videotaskevent.FieldID)
		for _, f := range fields {
			if !videotaskevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videotaskevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(videotaskevent.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(videotaskevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(videotaskevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, videotaskevent.FieldPayload, value)
		})
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(videotaskevent.FieldPayload, field.TypeJSON)
	}
	_node = &VideoTaskEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotaskevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
