// Code generated by ent, DO NOT EDIT.

package videopricingrule

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the videopricingrule type in the database.
	Label = "video_pricing_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldExternalModel holds the string denoting the external_model field in the database.
	FieldExternalModel = "external_model"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldResolution holds the string denoting the resolution field in the database.
	FieldResolution = "resolution"
	// FieldAudioMode holds the string denoting the audio_mode field in the database.
	FieldAudioMode = "audio_mode"
	// FieldUnit holds the string denoting the unit field in the database.
	FieldUnit = "unit"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldUpstreamUnitCost holds the string denoting the upstream_unit_cost field in the database.
	FieldUpstreamUnitCost = "upstream_unit_cost"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the videopricingrule in the database.
	Table = "video_pricing_rules"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "video_pricing_rules"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for videopricingrule fields.
var Columns = []string{
	FieldID,
	FieldGroupID,
	FieldExternalModel,
	FieldOperation,
	FieldResolution,
	FieldAudioMode,
	FieldUnit,
	FieldUnitPrice,
	FieldUpstreamUnitCost,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ExternalModelValidator is a validator for the "external_model" field. It is called by the builders before save.
	ExternalModelValidator func(string) error
	// DefaultResolution holds the default value on creation for the "resolution" field.
	DefaultResolution string
	// ResolutionValidator is a validator for the "resolution" field. It is called by the builders before save.
	ResolutionValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Operation defines the type for the "operation" enum field.
type Operation string

// Operation values.
const (
	OperationGeneration Operation = "generation"
	OperationEdit       Operation = "edit"
	OperationExtension  Operation = "extension"
)

func (o Operation) String() string {
	return string(o)
}

// OperationValidator is a validator for the "operation" field enum values. It is called by the builders before save.
func OperationValidator(o Operation) error {
	switch o {
	case OperationGeneration, OperationEdit, OperationExtension:
		return nil
	default:
		return fmt.Errorf("videopricingrule: invalid enum value for operation field: %q", o)
	}
}

// AudioMode defines the type for the "audio_mode" enum field.
type AudioMode string

// AudioModeAny is the default value of the AudioMode enum.
const DefaultAudioMode = AudioModeAny

// AudioMode values.
const (
	AudioModeAny          AudioMode = "any"
	AudioModeWithAudio    AudioMode = "with_audio"
	AudioModeWithoutAudio AudioMode = "without_audio"
)

func (am AudioMode) String() string {
	return string(am)
}

// AudioModeValidator is a validator for the "audio_mode" field enum values. It is called by the builders before save.
func AudioModeValidator(am AudioMode) error {
	switch am {
	case AudioModeAny, AudioModeWithAudio, AudioModeWithoutAudio:
		return nil
	default:
		return fmt.Errorf("videopricingrule: invalid enum value for audio_mode field: %q", am)
	}
}

// Unit defines the type for the "unit" enum field.
type Unit string

// Unit values.
const (
	UnitPerRequest      Unit = "per_request"
	UnitPerOutputSecond Unit = "per_output_second"
)

func (u Unit) String() string {
	return string(u)
}

// UnitValidator is a validator for the "unit" field enum values. It is called by the builders before save.
func UnitValidator(u Unit) error {
	switch u {
	case UnitPerRequest, UnitPerOutputSecond:
		return nil
	default:
		return fmt.Errorf("videopricingrule: invalid enum value for unit field: %q", u)
	}
}

// OrderOption defines the ordering options for the VideoPricingRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByExternalModel orders the results by the external_model field.
func ByExternalModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalModel, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByResolution orders the results by the resolution field.
func ByResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolution, opts...).ToFunc()
}

// ByAudioMode orders the results by the audio_mode field.
func ByAudioMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudioMode, opts...).ToFunc()
}

// ByUnit orders the results by the unit field.
func ByUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnit, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByUpstreamUnitCost orders the results by the upstream_unit_cost field.
func ByUpstreamUnitCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamUnitCost, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
