// Code generated by ent, DO NOT EDIT.

package videopricingrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldGroupID, v))
}

// ExternalModel applies equality check predicate on the "external_model" field. It's identical to ExternalModelEQ.
func ExternalModel(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldExternalModel, v))
}

// Resolution applies equality check predicate on the "resolution" field. It's identical to ResolutionEQ.
func Resolution(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldResolution, v))
}

// UnitPrice applies equality check predicate on the "unit_price" field. It's identical to UnitPriceEQ.
func UnitPrice(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldUnitPrice, v))
}

// UpstreamUnitCost applies equality check predicate on the "upstream_unit_cost" field. It's identical to UpstreamUnitCostEQ.
func UpstreamUnitCost(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldUpstreamUnitCost, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldGroupID, vs...))
}

// ExternalModelEQ applies the EQ predicate on the "external_model" field.
func ExternalModelEQ(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldExternalModel, v))
}

// ExternalModelNEQ applies the NEQ predicate on the "external_model" field.
func ExternalModelNEQ(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldExternalModel, v))
}

// ExternalModelIn applies the In predicate on the "external_model" field.
func ExternalModelIn(vs ...string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldExternalModel, vs...))
}

// ExternalModelNotIn applies the NotIn predicate on the "external_model" field.
func ExternalModelNotIn(vs ...string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldExternalModel, vs...))
}

// ExternalModelGT applies the GT predicate on the "external_model" field.
func ExternalModelGT(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGT(FieldExternalModel, v))
}

// ExternalModelGTE applies the GTE predicate on the "external_model" field.
func ExternalModelGTE(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGTE(FieldExternalModel, v))
}

// ExternalModelLT applies the LT predicate on the "external_model" field.
func ExternalModelLT(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLT(FieldExternalModel, v))
}

// ExternalModelLTE applies the LTE predicate on the "external_model" field.
func ExternalModelLTE(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLTE(FieldExternalModel, v))
}

// ExternalModelContains applies the Contains predicate on the "external_model" field.
func ExternalModelContains(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldContains(FieldExternalModel, v))
}

// ExternalModelHasPrefix applies the HasPrefix predicate on the "external_model" field.
func ExternalModelHasPrefix(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldHasPrefix(FieldExternalModel, v))
}

// ExternalModelHasSuffix applies the HasSuffix predicate on the "external_model" field.
func ExternalModelHasSuffix(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldHasSuffix(FieldExternalModel, v))
}

// ExternalModelEqualFold applies the EqualFold predicate on the "external_model" field.
func ExternalModelEqualFold(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEqualFold(FieldExternalModel, v))
}

// ExternalModelContainsFold applies the ContainsFold predicate on the "external_model" field.
func ExternalModelContainsFold(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldContainsFold(FieldExternalModel, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v Operation) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v Operation) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...Operation) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...Operation) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldOperation, vs...))
}

// ResolutionEQ applies the EQ predicate on the "resolution" field.
func ResolutionEQ(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldResolution, v))
}

// ResolutionNEQ applies the NEQ predicate on the "resolution" field.
func ResolutionNEQ(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldResolution, v))
}

// ResolutionIn applies the In predicate on the "resolution" field.
func ResolutionIn(vs ...string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldResolution, vs...))
}

// ResolutionNotIn applies the NotIn predicate on the "resolution" field.
func ResolutionNotIn(vs ...string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldResolution, vs...))
}

// ResolutionGT applies the GT predicate on the "resolution" field.
func ResolutionGT(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGT(FieldResolution, v))
}

// ResolutionGTE applies the GTE predicate on the "resolution" field.
func ResolutionGTE(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGTE(FieldResolution, v))
}

// ResolutionLT applies the LT predicate on the "resolution" field.
func ResolutionLT(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLT(FieldResolution, v))
}

// ResolutionLTE applies the LTE predicate on the "resolution" field.
func ResolutionLTE(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLTE(FieldResolution, v))
}

// ResolutionContains applies the Contains predicate on the "resolution" field.
func ResolutionContains(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldContains(FieldResolution, v))
}

// ResolutionHasPrefix applies the HasPrefix predicate on the "resolution" field.
func ResolutionHasPrefix(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldHasPrefix(FieldResolution, v))
}

// ResolutionHasSuffix applies the HasSuffix predicate on the "resolution" field.
func ResolutionHasSuffix(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldHasSuffix(FieldResolution, v))
}

// ResolutionEqualFold applies the EqualFold predicate on the "resolution" field.
func ResolutionEqualFold(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEqualFold(FieldResolution, v))
}

// ResolutionContainsFold applies the ContainsFold predicate on the "resolution" field.
func ResolutionContainsFold(v string) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldContainsFold(FieldResolution, v))
}

// AudioModeEQ applies the EQ predicate on the "audio_mode" field.
func AudioModeEQ(v AudioMode) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldAudioMode, v))
}

// AudioModeNEQ applies the NEQ predicate on the "audio_mode" field.
func AudioModeNEQ(v AudioMode) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldAudioMode, v))
}

// AudioModeIn applies the In predicate on the "audio_mode" field.
func AudioModeIn(vs ...AudioMode) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldAudioMode, vs...))
}

// AudioModeNotIn applies the NotIn predicate on the "audio_mode" field.
func AudioModeNotIn(vs ...AudioMode) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldAudioMode, vs...))
}

// UnitEQ applies the EQ predicate on the "unit" field.
func UnitEQ(v Unit) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldUnit, v))
}

// UnitNEQ applies the NEQ predicate on the "unit" field.
func UnitNEQ(v Unit) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldUnit, v))
}

// UnitIn applies the In predicate on the "unit" field.
func UnitIn(vs ...Unit) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldUnit, vs...))
}

// UnitNotIn applies the NotIn predicate on the "unit" field.
func UnitNotIn(vs ...Unit) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldUnit, vs...))
}

// UnitPriceEQ applies the EQ predicate on the "unit_price" field.
func UnitPriceEQ(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldUnitPrice, v))
}

// UnitPriceNEQ applies the NEQ predicate on the "unit_price" field.
func UnitPriceNEQ(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldUnitPrice, v))
}

// UnitPriceIn applies the In predicate on the "unit_price" field.
func UnitPriceIn(vs ...float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldUnitPrice, vs...))
}

// UnitPriceNotIn applies the NotIn predicate on the "unit_price" field.
func UnitPriceNotIn(vs ...float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldUnitPrice, vs...))
}

// UnitPriceGT applies the GT predicate on the "unit_price" field.
func UnitPriceGT(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGT(FieldUnitPrice, v))
}

// UnitPriceGTE applies the GTE predicate on the "unit_price" field.
func UnitPriceGTE(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGTE(FieldUnitPrice, v))
}

// UnitPriceLT applies the LT predicate on the "unit_price" field.
func UnitPriceLT(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLT(FieldUnitPrice, v))
}

// UnitPriceLTE applies the LTE predicate on the "unit_price" field.
func UnitPriceLTE(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLTE(FieldUnitPrice, v))
}

// UpstreamUnitCostEQ applies the EQ predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostEQ(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldUpstreamUnitCost, v))
}

// UpstreamUnitCostNEQ applies the NEQ predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostNEQ(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldUpstreamUnitCost, v))
}

// UpstreamUnitCostIn applies the In predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostIn(vs ...float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldUpstreamUnitCost, vs...))
}

// UpstreamUnitCostNotIn applies the NotIn predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostNotIn(vs ...float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldUpstreamUnitCost, vs...))
}

// UpstreamUnitCostGT applies the GT predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostGT(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGT(FieldUpstreamUnitCost, v))
}

// UpstreamUnitCostGTE applies the GTE predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostGTE(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGTE(FieldUpstreamUnitCost, v))
}

// UpstreamUnitCostLT applies the LT predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostLT(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLT(FieldUpstreamUnitCost, v))
}

// UpstreamUnitCostLTE applies the LTE predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostLTE(v float64) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLTE(FieldUpstreamUnitCost, v))
}

// UpstreamUnitCostIsNil applies the IsNil predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostIsNil() predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIsNull(FieldUpstreamUnitCost))
}

// UpstreamUnitCostNotNil applies the NotNil predicate on the "upstream_unit_cost" field.
func UpstreamUnitCostNotNil() predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotNull(FieldUpstreamUnitCost))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.VideoPricingRule {
	return predicate.VideoPricingRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VideoPricingRule) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VideoPricingRule) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VideoPricingRule) predicate.VideoPricingRule {
	return predicate.VideoPricingRule(sql.NotPredicates(p))
}
